// Package openaiservice provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package openaiservice

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"mime/multipart"

	"github.com/gofiber/fiber/v2"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for ChatCompletionResponseMessageRole.
const (
	ChatCompletionResponseMessageRoleAssistant ChatCompletionResponseMessageRole = "assistant"
)

// Valid indicates whether the value is a known member of the ChatCompletionResponseMessageRole enum.
func (e ChatCompletionResponseMessageRole) Valid() bool {
	switch e {
	case ChatCompletionResponseMessageRoleAssistant:
		return true
	default:
		return false
	}
}

// Defines values for ChatCompletionStreamResponseDeltaRole.
const (
	ChatCompletionStreamResponseDeltaRoleAssistant ChatCompletionStreamResponseDeltaRole = "assistant"
)

// Valid indicates whether the value is a known member of the ChatCompletionStreamResponseDeltaRole enum.
func (e ChatCompletionStreamResponseDeltaRole) Valid() bool {
	switch e {
	case ChatCompletionStreamResponseDeltaRoleAssistant:
		return true
	default:
		return false
	}
}

// Defines values for CreateChatCompletionStreamResponseObject.
const (
	ChatCompletionChunk CreateChatCompletionStreamResponseObject = "chat.completion.chunk"
)

// Valid indicates whether the value is a known member of the CreateChatCompletionStreamResponseObject enum.
func (e CreateChatCompletionStreamResponseObject) Valid() bool {
	switch e {
	case ChatCompletionChunk:
		return true
	default:
		return false
	}
}

// Defines values for ModelObject.
const (
	ModelObjectModel ModelObject = "model"
)

// Valid indicates whether the value is a known member of the ModelObject enum.
func (e ModelObject) Valid() bool {
	switch e {
	case ModelObjectModel:
		return true
	default:
		return false
	}
}

// ChatCompletionChoice defines model for ChatCompletionChoice.
type ChatCompletionChoice struct {
	FinishReason *string                       `json:"finish_reason"`
	Index        int                           `json:"index"`
	Message      ChatCompletionResponseMessage `json:"message"`
}

// ChatCompletionChunkChoice defines model for ChatCompletionChunkChoice.
type ChatCompletionChunkChoice struct {
	Delta        ChatCompletionStreamResponseDelta `json:"delta"`
	FinishReason *string                           `json:"finish_reason,omitempty"`
	Index        int                               `json:"index"`
}

// ChatCompletionResponseMessage defines model for ChatCompletionResponseMessage.
type ChatCompletionResponseMessage struct {
	Content *string                           `json:"content"`
	Role    ChatCompletionResponseMessageRole `json:"role"`
}

// ChatCompletionResponseMessageRole defines model for ChatCompletionResponseMessage.Role.
type ChatCompletionResponseMessageRole string

// ChatCompletionStreamResponseDelta defines model for ChatCompletionStreamResponseDelta.
type ChatCompletionStreamResponseDelta struct {
	Content *string                                `json:"content,omitempty"`
	Role    *ChatCompletionStreamResponseDeltaRole `json:"role,omitempty"`
}

// ChatCompletionStreamResponseDeltaRole defines model for ChatCompletionStreamResponseDelta.Role.
type ChatCompletionStreamResponseDeltaRole string

// CreateChatCompletionRequest defines model for CreateChatCompletionRequest.
type CreateChatCompletionRequest struct {
	Messages []map[string]interface{} `json:"messages"`
	Model    string                   `json:"model"`
	Stream   *bool                    `json:"stream,omitempty"`
}

// CreateChatCompletionResponse defines model for CreateChatCompletionResponse.
type CreateChatCompletionResponse struct {
	Choices []ChatCompletionChoice `json:"choices"`
	Created int64                  `json:"created"`
	Id      string                 `json:"id"`
	Model   string                 `json:"model"`
	Object  string                 `json:"object"`
}

// CreateChatCompletionStreamResponse defines model for CreateChatCompletionStreamResponse.
type CreateChatCompletionStreamResponse struct {
	Choices []ChatCompletionChunkChoice              `json:"choices"`
	Created int64                                    `json:"created"`
	Id      string                                   `json:"id"`
	Model   string                                   `json:"model"`
	Object  CreateChatCompletionStreamResponseObject `json:"object"`
}

// CreateChatCompletionStreamResponseObject defines model for CreateChatCompletionStreamResponse.Object.
type CreateChatCompletionStreamResponseObject string

// CreateSpeechRequest defines model for CreateSpeechRequest.
type CreateSpeechRequest struct {
	Input          string   `json:"input"`
	Model          string   `json:"model"`
	ResponseFormat *string  `json:"response_format,omitempty"`
	Speed          *float32 `json:"speed,omitempty"`
	Stream         *bool    `json:"stream,omitempty"`
	Voice          string   `json:"voice"`
}

// CreateSpeechResponseStreamEvent defines model for CreateSpeechResponseStreamEvent.
type CreateSpeechResponseStreamEvent struct {
	// Audio Base64 encoded audio delta.
	Audio *string `json:"audio,omitempty"`
	Done  *bool   `json:"done,omitempty"`
	Type  string  `json:"type"`
}

// CreateTranscriptionRequest defines model for CreateTranscriptionRequest.
type CreateTranscriptionRequest struct {
	File           openapi_types.File `json:"file"`
	Model          string             `json:"model"`
	ResponseFormat *string            `json:"response_format,omitempty"`
	Stream         *bool              `json:"stream,omitempty"`
}

// CreateTranscriptionResponseJson defines model for CreateTranscriptionResponseJson.
type CreateTranscriptionResponseJson struct {
	Text string `json:"text"`
}

// CreateTranscriptionResponseStreamEvent defines model for CreateTranscriptionResponseStreamEvent.
type CreateTranscriptionResponseStreamEvent struct {
	Delta *string `json:"delta,omitempty"`
	Text  *string `json:"text,omitempty"`
	Type  string  `json:"type"`
}

// ListModelsResponse defines model for ListModelsResponse.
type ListModelsResponse struct {
	Data   []Model `json:"data"`
	Object string  `json:"object"`
}

// Model defines model for Model.
type Model struct {
	Created int64       `json:"created"`
	Id      string      `json:"id"`
	Object  ModelObject `json:"object"`
	OwnedBy string      `json:"owned_by"`
}

// ModelObject defines model for Model.Object.
type ModelObject string

// CreateSpeechJSONRequestBody defines body for CreateSpeech for application/json ContentType.
type CreateSpeechJSONRequestBody = CreateSpeechRequest

// CreateTranscriptionMultipartRequestBody defines body for CreateTranscription for multipart/form-data ContentType.
type CreateTranscriptionMultipartRequestBody = CreateTranscriptionRequest

// CreateChatCompletionJSONRequestBody defines body for CreateChatCompletion for application/json ContentType.
type CreateChatCompletionJSONRequestBody = CreateChatCompletionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create speech
	// (POST /audio/speech)
	CreateSpeech(c *fiber.Ctx) error
	// Create transcription
	// (POST /audio/transcriptions)
	CreateTranscription(c *fiber.Ctx) error
	// Create chat completion
	// (POST /chat/completions)
	CreateChatCompletion(c *fiber.Ctx) error
	// List models
	// (GET /models)
	ListModels(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// CreateSpeech operation middleware
func (siw *ServerInterfaceWrapper) CreateSpeech(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.CreateSpeech(c)
}

// CreateTranscription operation middleware
func (siw *ServerInterfaceWrapper) CreateTranscription(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.CreateTranscription(c)
}

// CreateChatCompletion operation middleware
func (siw *ServerInterfaceWrapper) CreateChatCompletion(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.CreateChatCompletion(c)
}

// ListModels operation middleware
func (siw *ServerInterfaceWrapper) ListModels(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.ListModels(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Post(options.BaseURL+"/audio/speech", wrapper.CreateSpeech)

	router.Post(options.BaseURL+"/audio/transcriptions", wrapper.CreateTranscription)

	router.Post(options.BaseURL+"/chat/completions", wrapper.CreateChatCompletion)

	router.Get(options.BaseURL+"/models", wrapper.ListModels)

}

type CreateSpeechRequestObject struct {
	Body *CreateSpeechJSONRequestBody
}

type CreateSpeechResponseObject interface {
	VisitCreateSpeechResponse(ctx *fiber.Ctx) error
}

type CreateSpeech200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response CreateSpeech200ApplicationoctetStreamResponse) VisitCreateSpeechResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		ctx.Response().Header.Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	ctx.Status(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(ctx.Response().BodyWriter(), response.Body)
	return err
}

type CreateSpeech200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response CreateSpeech200TexteventStreamResponse) VisitCreateSpeechResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		ctx.Response().Header.Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	ctx.Status(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(ctx.Response().BodyWriter(), response.Body)
	return err
}

type CreateTranscriptionRequestObject struct {
	Body *multipart.Reader
}

type CreateTranscriptionResponseObject interface {
	VisitCreateTranscriptionResponse(ctx *fiber.Ctx) error
}

type CreateTranscription200JSONResponse CreateTranscriptionResponseJson

func (response CreateTranscription200JSONResponse) VisitCreateTranscriptionResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type CreateTranscription200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response CreateTranscription200TexteventStreamResponse) VisitCreateTranscriptionResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		ctx.Response().Header.Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	ctx.Status(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(ctx.Response().BodyWriter(), response.Body)
	return err
}

type CreateChatCompletionRequestObject struct {
	Body *CreateChatCompletionJSONRequestBody
}

type CreateChatCompletionResponseObject interface {
	VisitCreateChatCompletionResponse(ctx *fiber.Ctx) error
}

type CreateChatCompletion200JSONResponse CreateChatCompletionResponse

func (response CreateChatCompletion200JSONResponse) VisitCreateChatCompletionResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type CreateChatCompletion200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response CreateChatCompletion200TexteventStreamResponse) VisitCreateChatCompletionResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		ctx.Response().Header.Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	ctx.Status(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(ctx.Response().BodyWriter(), response.Body)
	return err
}

type ListModelsRequestObject struct {
}

type ListModelsResponseObject interface {
	VisitListModelsResponse(ctx *fiber.Ctx) error
}

type ListModels200JSONResponse ListModelsResponse

func (response ListModels200JSONResponse) VisitListModelsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create speech
	// (POST /audio/speech)
	CreateSpeech(ctx context.Context, request CreateSpeechRequestObject) (CreateSpeechResponseObject, error)
	// Create transcription
	// (POST /audio/transcriptions)
	CreateTranscription(ctx context.Context, request CreateTranscriptionRequestObject) (CreateTranscriptionResponseObject, error)
	// Create chat completion
	// (POST /chat/completions)
	CreateChatCompletion(ctx context.Context, request CreateChatCompletionRequestObject) (CreateChatCompletionResponseObject, error)
	// List models
	// (GET /models)
	ListModels(ctx context.Context, request ListModelsRequestObject) (ListModelsResponseObject, error)
}

type StrictHandlerFunc func(ctx *fiber.Ctx, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// CreateSpeech operation middleware
func (sh *strictHandler) CreateSpeech(ctx *fiber.Ctx) error {
	var request CreateSpeechRequestObject

	var body CreateSpeechJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSpeech(ctx.UserContext(), request.(CreateSpeechRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSpeech")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(CreateSpeechResponseObject); ok {
		if err := validResponse.VisitCreateSpeechResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateTranscription operation middleware
func (sh *strictHandler) CreateTranscription(ctx *fiber.Ctx) error {
	var request CreateTranscriptionRequestObject

	request.Body = multipart.NewReader(bytes.NewReader(ctx.Request().Body()), string(ctx.Request().Header.MultipartFormBoundary()))

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTranscription(ctx.UserContext(), request.(CreateTranscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTranscription")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(CreateTranscriptionResponseObject); ok {
		if err := validResponse.VisitCreateTranscriptionResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateChatCompletion operation middleware
func (sh *strictHandler) CreateChatCompletion(ctx *fiber.Ctx) error {
	var request CreateChatCompletionRequestObject

	var body CreateChatCompletionJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreateChatCompletion(ctx.UserContext(), request.(CreateChatCompletionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateChatCompletion")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(CreateChatCompletionResponseObject); ok {
		if err := validResponse.VisitCreateChatCompletionResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListModels operation middleware
func (sh *strictHandler) ListModels(ctx *fiber.Ctx) error {
	var request ListModelsRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.ListModels(ctx.UserContext(), request.(ListModelsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListModels")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(ListModelsResponseObject); ok {
		if err := validResponse.VisitListModelsResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
