// Package gizclaw provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package gizclaw

import (
	"encoding/json"
)

// Event defines model for Event.
type Event struct {
	Data *json.RawMessage `json:"data,omitempty"`
	Name string           `json:"name"`
	V    int              `json:"v"`
}
