// Package rpc provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package rpc

// PingRequest defines model for PingRequest.
type PingRequest struct {
	ClientSendTime int64 `json:"client_send_time"`
}

// PingResponse defines model for PingResponse.
type PingResponse struct {
	ServerTime int64 `json:"server_time"`
}

// RPCError defines model for RPCError.
type RPCError struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// RPCRequest defines model for RPCRequest.
type RPCRequest struct {
	Id     string       `json:"id"`
	Method string       `json:"method"`
	Params *PingRequest `json:"params,omitempty"`
	V      int          `json:"v"`
}

// RPCResponse defines model for RPCResponse.
type RPCResponse struct {
	Error  *RPCError     `json:"error,omitempty"`
	Id     string        `json:"id"`
	Result *PingResponse `json:"result,omitempty"`
	V      int           `json:"v"`
}
