// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetChannelData, GetChannelErrors, GetChannelResponses, GetDepotData, GetDepotErrors, GetDepotResponses, ListDepotsData, ListDepotsErrors, ListDepotsResponses, PutChannelData, PutChannelErrors, PutChannelResponses, PutDepotInfoData, PutDepotInfoErrors, PutDepotInfoResponses, ReleaseDepotData, ReleaseDepotErrors, ReleaseDepotResponses, RollbackDepotData, RollbackDepotErrors, RollbackDepotResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List all firmware depots
 */
export const listDepots = <ThrowOnError extends boolean = false>(options?: Options<ListDepotsData, ThrowOnError>) => (options?.client ?? client).get<ListDepotsResponses, ListDepotsErrors, ThrowOnError>({ url: '/firmwares', ...options });

/**
 * Get a firmware depot snapshot
 */
export const getDepot = <ThrowOnError extends boolean = false>(options: Options<GetDepotData, ThrowOnError>) => (options.client ?? client).get<GetDepotResponses, GetDepotErrors, ThrowOnError>({ url: '/firmwares/{depot}', ...options });

/**
 * Create or update depot info (file manifest)
 */
export const putDepotInfo = <ThrowOnError extends boolean = false>(options: Options<PutDepotInfoData, ThrowOnError>) => (options.client ?? client).put<PutDepotInfoResponses, PutDepotInfoErrors, ThrowOnError>({
    url: '/firmwares/{depot}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Promote testing channel to stable
 */
export const releaseDepot = <ThrowOnError extends boolean = false>(options: Options<ReleaseDepotData, ThrowOnError>) => (options.client ?? client).put<ReleaseDepotResponses, ReleaseDepotErrors, ThrowOnError>({ url: '/firmwares/{depot}/@release', ...options });

/**
 * Roll back stable channel to the rollback snapshot
 */
export const rollbackDepot = <ThrowOnError extends boolean = false>(options: Options<RollbackDepotData, ThrowOnError>) => (options.client ?? client).put<RollbackDepotResponses, RollbackDepotErrors, ThrowOnError>({ url: '/firmwares/{depot}/@rollback', ...options });

/**
 * Get a specific channel release
 */
export const getChannel = <ThrowOnError extends boolean = false>(options: Options<GetChannelData, ThrowOnError>) => (options.client ?? client).get<GetChannelResponses, GetChannelErrors, ThrowOnError>({ url: '/firmwares/{depot}/{channel}', ...options });

/**
 * Upload a firmware release tarball for a channel
 */
export const putChannel = <ThrowOnError extends boolean = false>(options: Options<PutChannelData, ThrowOnError>) => (options.client ?? client).put<PutChannelResponses, PutChannelErrors, ThrowOnError>({
    bodySerializer: null,
    url: '/firmwares/{depot}/{channel}',
    ...options,
    headers: {
        'Content-Type': 'application/octet-stream',
        ...options.headers
    }
});
