// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Channel = string;

export type Depot = {
    name: string;
    info: DepotInfo;
    rollback: DepotRelease;
    stable: DepotRelease;
    beta: DepotRelease;
    testing: DepotRelease;
};

export type DepotList = {
    items: Array<Depot>;
};

export type DepotInfo = {
    files?: Array<DepotInfoFile>;
};

export type DepotInfoFile = {
    path: string;
};

export type DepotRelease = {
    firmware_semver: string;
    channel?: string;
    files?: Array<DepotFile>;
};

export type RegistrationList = {
    has_next: boolean;
    next_cursor?: string | null;
    items: Array<Registration>;
};

export type RefreshResult = {
    gear: Gear;
    updated_fields?: Array<string>;
    errors?: Array<string>;
};

export type PublicKeyResponse = {
    public_key: string;
};

export type ApproveRequest = {
    role: GearRole;
};

export type Configuration = {
    certifications?: Array<GearCertification>;
    firmware?: FirmwareConfig;
};

export type DepotFile = {
    path: string;
    sha256: string;
    md5: string;
};

export type DeviceInfo = {
    name?: string;
    sn?: string;
    hardware?: HardwareInfo;
};

export type ErrorPayload = {
    code: string;
    message: string;
    details?: {
        [key: string]: unknown;
    };
};

export type ErrorResponse = {
    error: ErrorPayload;
};

export type FirmwareConfig = {
    channel?: GearFirmwareChannel;
};

export type Gear = {
    public_key: string;
    role: GearRole;
    status: GearStatus;
    device: DeviceInfo;
    configuration: Configuration;
    auto_registered?: boolean;
    created_at: string;
    updated_at: string;
    approved_at?: string;
};

export type GearCertification = {
    type: GearCertificationType;
    authority: GearCertificationAuthority;
    id: string;
    authority_name?: string;
};

export type GearCertificationAuthority = 'unknown' | 'ccc' | 'ce' | 'fcc' | 'miit' | 'srrc' | 'rohs' | 'internal';

export type GearCertificationType = 'license' | 'certification';

export type GearFirmwareChannel = string;

export type GearImei = {
    name?: string;
    tac: string;
    serial: string;
};

export type GearLabel = {
    key: string;
    value: string;
};

export type GearRole = 'unspecified' | 'admin' | 'peer' | 'device';

export type GearStatus = 'unspecified' | 'active' | 'blocked';

export type HardwareInfo = {
    manufacturer?: string;
    model?: string;
    hardware_revision?: string;
    depot?: string;
    firmware_semver?: string;
    imeis?: Array<GearImei>;
    labels?: Array<GearLabel>;
};

export type OtaSummary = {
    depot: string;
    channel: string;
    firmware_semver: string;
    files: Array<DepotFile>;
};

export type Registration = {
    public_key: string;
    role: GearRole;
    status: GearStatus;
    auto_registered?: boolean;
    created_at: string;
    updated_at: string;
    approved_at?: string;
};

export type Runtime = {
    online: boolean;
    last_seen_at: string;
    last_addr?: string;
};

/**
 * Opaque cursor returned by the previous list response
 */
export type Cursor = string;

/**
 * Maximum number of items to return
 */
export type Limit = number;

/**
 * Firmware depot name
 */
export type DepotName = string;

/**
 * Release channel
 */
export type Channel2 = Channel;

/**
 * Gear public key
 */
export type PublicKey = string;

export type ListDepotsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/firmwares';
};

export type ListDepotsErrors = {
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type ListDepotsError = ListDepotsErrors[keyof ListDepotsErrors];

export type ListDepotsResponses = {
    /**
     * Depot list
     */
    200: DepotList;
};

export type ListDepotsResponse = ListDepotsResponses[keyof ListDepotsResponses];

export type GetDepotData = {
    body?: never;
    path: {
        /**
         * Firmware depot name
         */
        depot: string;
    };
    query?: never;
    url: '/firmwares/{depot}';
};

export type GetDepotErrors = {
    /**
     * Depot not found
     */
    404: ErrorResponse;
};

export type GetDepotError = GetDepotErrors[keyof GetDepotErrors];

export type GetDepotResponses = {
    /**
     * Depot snapshot
     */
    200: Depot;
};

export type GetDepotResponse = GetDepotResponses[keyof GetDepotResponses];

export type PutDepotInfoData = {
    body: DepotInfo;
    path: {
        /**
         * Firmware depot name
         */
        depot: string;
    };
    query?: never;
    url: '/firmwares/{depot}';
};

export type PutDepotInfoErrors = {
    /**
     * Invalid JSON
     */
    400: ErrorResponse;
    /**
     * Info conflicts with existing releases
     */
    409: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type PutDepotInfoError = PutDepotInfoErrors[keyof PutDepotInfoErrors];

export type PutDepotInfoResponses = {
    /**
     * Updated depot snapshot
     */
    200: Depot;
};

export type PutDepotInfoResponse = PutDepotInfoResponses[keyof PutDepotInfoResponses];

export type ReleaseDepotData = {
    body?: never;
    path: {
        /**
         * Firmware depot name
         */
        depot: string;
    };
    query?: never;
    url: '/firmwares/{depot}/@release';
};

export type ReleaseDepotErrors = {
    /**
     * Depot not found
     */
    404: ErrorResponse;
    /**
     * Release not ready (testing channel missing)
     */
    409: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type ReleaseDepotError = ReleaseDepotErrors[keyof ReleaseDepotErrors];

export type ReleaseDepotResponses = {
    /**
     * Updated depot snapshot after release
     */
    200: Depot;
};

export type ReleaseDepotResponse = ReleaseDepotResponses[keyof ReleaseDepotResponses];

export type RollbackDepotData = {
    body?: never;
    path: {
        /**
         * Firmware depot name
         */
        depot: string;
    };
    query?: never;
    url: '/firmwares/{depot}/@rollback';
};

export type RollbackDepotErrors = {
    /**
     * Depot not found
     */
    404: ErrorResponse;
    /**
     * Rollback not available
     */
    409: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type RollbackDepotError = RollbackDepotErrors[keyof RollbackDepotErrors];

export type RollbackDepotResponses = {
    /**
     * Updated depot snapshot after rollback
     */
    200: Depot;
};

export type RollbackDepotResponse = RollbackDepotResponses[keyof RollbackDepotResponses];

export type GetChannelData = {
    body?: never;
    path: {
        /**
         * Firmware depot name
         */
        depot: string;
        /**
         * Release channel
         */
        channel: Channel;
    };
    query?: never;
    url: '/firmwares/{depot}/{channel}';
};

export type GetChannelErrors = {
    /**
     * Depot or channel not found
     */
    404: ErrorResponse;
};

export type GetChannelError = GetChannelErrors[keyof GetChannelErrors];

export type GetChannelResponses = {
    /**
     * Channel release
     */
    200: DepotRelease;
};

export type GetChannelResponse = GetChannelResponses[keyof GetChannelResponses];

export type PutChannelData = {
    body: Blob | File;
    path: {
        /**
         * Firmware depot name
         */
        depot: string;
        /**
         * Release channel
         */
        channel: Channel;
    };
    query?: never;
    url: '/firmwares/{depot}/{channel}';
};

export type PutChannelErrors = {
    /**
     * Invalid manifest in tarball
     */
    409: ErrorResponse;
};

export type PutChannelError = PutChannelErrors[keyof PutChannelErrors];

export type PutChannelResponses = {
    /**
     * Uploaded release
     */
    200: DepotRelease;
};

export type PutChannelResponse = PutChannelResponses[keyof PutChannelResponses];

export type ListGearsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Opaque cursor returned by the previous list response
         */
        cursor?: string;
        /**
         * Maximum number of items to return
         */
        limit?: number;
    };
    url: '/gears';
};

export type ListGearsErrors = {
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type ListGearsError = ListGearsErrors[keyof ListGearsErrors];

export type ListGearsResponses = {
    /**
     * Gear registration list
     */
    200: RegistrationList;
};

export type ListGearsResponse = ListGearsResponses[keyof ListGearsResponses];

export type ResolveBySnData = {
    body?: never;
    path: {
        sn: string;
    };
    query?: never;
    url: '/gears/sn/{sn}';
};

export type ResolveBySnErrors = {
    /**
     * Gear not found
     */
    404: ErrorResponse;
};

export type ResolveBySnError = ResolveBySnErrors[keyof ResolveBySnErrors];

export type ResolveBySnResponses = {
    /**
     * Resolved public key
     */
    200: PublicKeyResponse;
};

export type ResolveBySnResponse = ResolveBySnResponses[keyof ResolveBySnResponses];

export type ResolveByImeiData = {
    body?: never;
    path: {
        tac: string;
        serial: string;
    };
    query?: never;
    url: '/gears/imei/{tac}/{serial}';
};

export type ResolveByImeiErrors = {
    /**
     * Gear not found
     */
    404: ErrorResponse;
};

export type ResolveByImeiError = ResolveByImeiErrors[keyof ResolveByImeiErrors];

export type ResolveByImeiResponses = {
    /**
     * Resolved public key
     */
    200: PublicKeyResponse;
};

export type ResolveByImeiResponse = ResolveByImeiResponses[keyof ResolveByImeiResponses];

export type ListByLabelData = {
    body?: never;
    path: {
        key: string;
        value: string;
    };
    query?: {
        /**
         * Opaque cursor returned by the previous list response
         */
        cursor?: string;
        /**
         * Maximum number of items to return
         */
        limit?: number;
    };
    url: '/gears/label/{key}/{value}';
};

export type ListByLabelErrors = {
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type ListByLabelError = ListByLabelErrors[keyof ListByLabelErrors];

export type ListByLabelResponses = {
    /**
     * Matched gears
     */
    200: RegistrationList;
};

export type ListByLabelResponse = ListByLabelResponses[keyof ListByLabelResponses];

export type ListByCertificationData = {
    body?: never;
    path: {
        type: GearCertificationType;
        authority: GearCertificationAuthority;
        id: string;
    };
    query?: {
        /**
         * Opaque cursor returned by the previous list response
         */
        cursor?: string;
        /**
         * Maximum number of items to return
         */
        limit?: number;
    };
    url: '/gears/certification/{type}/{authority}/{id}';
};

export type ListByCertificationErrors = {
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type ListByCertificationError = ListByCertificationErrors[keyof ListByCertificationErrors];

export type ListByCertificationResponses = {
    /**
     * Matched gears
     */
    200: RegistrationList;
};

export type ListByCertificationResponse = ListByCertificationResponses[keyof ListByCertificationResponses];

export type ListByFirmwareData = {
    body?: never;
    path: {
        depot: string;
        channel: GearFirmwareChannel;
    };
    query?: {
        /**
         * Opaque cursor returned by the previous list response
         */
        cursor?: string;
        /**
         * Maximum number of items to return
         */
        limit?: number;
    };
    url: '/gears/firmware/{depot}/{channel}';
};

export type ListByFirmwareErrors = {
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type ListByFirmwareError = ListByFirmwareErrors[keyof ListByFirmwareErrors];

export type ListByFirmwareResponses = {
    /**
     * Matched gears
     */
    200: RegistrationList;
};

export type ListByFirmwareResponse = ListByFirmwareResponses[keyof ListByFirmwareResponses];

export type DeleteGearData = {
    body?: never;
    path: {
        /**
         * Gear public key
         */
        publicKey: string;
    };
    query?: never;
    url: '/gears/{publicKey}';
};

export type DeleteGearErrors = {
    /**
     * Gear not found
     */
    404: ErrorResponse;
};

export type DeleteGearError = DeleteGearErrors[keyof DeleteGearErrors];

export type DeleteGearResponses = {
    /**
     * Deleted gear registration
     */
    200: Registration;
};

export type DeleteGearResponse = DeleteGearResponses[keyof DeleteGearResponses];

export type GetGearData = {
    body?: never;
    path: {
        /**
         * Gear public key
         */
        publicKey: string;
    };
    query?: never;
    url: '/gears/{publicKey}';
};

export type GetGearErrors = {
    /**
     * Gear not found
     */
    404: ErrorResponse;
};

export type GetGearError = GetGearErrors[keyof GetGearErrors];

export type GetGearResponses = {
    /**
     * Gear registration
     */
    200: Registration;
};

export type GetGearResponse = GetGearResponses[keyof GetGearResponses];

export type ApproveGearData = {
    body: ApproveRequest;
    path: {
        /**
         * Gear public key
         */
        publicKey: string;
    };
    query?: never;
    url: '/gears/{publicKey}/@approve';
};

export type ApproveGearErrors = {
    /**
     * Invalid role
     */
    400: ErrorResponse;
};

export type ApproveGearError = ApproveGearErrors[keyof ApproveGearErrors];

export type ApproveGearResponses = {
    /**
     * Approved gear registration
     */
    200: Registration;
};

export type ApproveGearResponse = ApproveGearResponses[keyof ApproveGearResponses];

export type BlockGearData = {
    body?: never;
    path: {
        /**
         * Gear public key
         */
        publicKey: string;
    };
    query?: never;
    url: '/gears/{publicKey}/@block';
};

export type BlockGearErrors = {
    /**
     * Gear not found
     */
    404: ErrorResponse;
};

export type BlockGearError = BlockGearErrors[keyof BlockGearErrors];

export type BlockGearResponses = {
    /**
     * Blocked gear registration
     */
    200: Registration;
};

export type BlockGearResponse = BlockGearResponses[keyof BlockGearResponses];

export type RefreshGearData = {
    body?: never;
    path: {
        /**
         * Gear public key
         */
        publicKey: string;
    };
    query?: never;
    url: '/gears/{publicKey}/@refresh';
};

export type RefreshGearErrors = {
    /**
     * Gear not found
     */
    404: ErrorResponse;
    /**
     * Device offline
     */
    409: ErrorResponse;
    /**
     * Device refresh failed
     */
    502: ErrorResponse;
};

export type RefreshGearError = RefreshGearErrors[keyof RefreshGearErrors];

export type RefreshGearResponses = {
    /**
     * Refresh result
     */
    200: RefreshResult;
};

export type RefreshGearResponse = RefreshGearResponses[keyof RefreshGearResponses];

export type GetGearInfoData = {
    body?: never;
    path: {
        /**
         * Gear public key
         */
        publicKey: string;
    };
    query?: never;
    url: '/gears/{publicKey}/info';
};

export type GetGearInfoErrors = {
    /**
     * Gear not found
     */
    404: ErrorResponse;
};

export type GetGearInfoError = GetGearInfoErrors[keyof GetGearInfoErrors];

export type GetGearInfoResponses = {
    /**
     * Device info
     */
    200: DeviceInfo;
};

export type GetGearInfoResponse = GetGearInfoResponses[keyof GetGearInfoResponses];

export type GetGearConfigData = {
    body?: never;
    path: {
        /**
         * Gear public key
         */
        publicKey: string;
    };
    query?: never;
    url: '/gears/{publicKey}/config';
};

export type GetGearConfigErrors = {
    /**
     * Gear not found
     */
    404: ErrorResponse;
};

export type GetGearConfigError = GetGearConfigErrors[keyof GetGearConfigErrors];

export type GetGearConfigResponses = {
    /**
     * Configuration
     */
    200: Configuration;
};

export type GetGearConfigResponse = GetGearConfigResponses[keyof GetGearConfigResponses];

export type PutGearConfigData = {
    body: Configuration;
    path: {
        /**
         * Gear public key
         */
        publicKey: string;
    };
    query?: never;
    url: '/gears/{publicKey}/config';
};

export type PutGearConfigErrors = {
    /**
     * Invalid params
     */
    400: ErrorResponse;
    /**
     * Gear not found
     */
    404: ErrorResponse;
};

export type PutGearConfigError = PutGearConfigErrors[keyof PutGearConfigErrors];

export type PutGearConfigResponses = {
    /**
     * Updated configuration
     */
    200: Configuration;
};

export type PutGearConfigResponse = PutGearConfigResponses[keyof PutGearConfigResponses];

export type GetGearRuntimeData = {
    body?: never;
    path: {
        /**
         * Gear public key
         */
        publicKey: string;
    };
    query?: never;
    url: '/gears/{publicKey}/runtime';
};

export type GetGearRuntimeResponses = {
    /**
     * Runtime status
     */
    200: Runtime;
};

export type GetGearRuntimeResponse = GetGearRuntimeResponses[keyof GetGearRuntimeResponses];

export type GetGearOtaData = {
    body?: never;
    path: {
        /**
         * Gear public key
         */
        publicKey: string;
    };
    query?: never;
    url: '/gears/{publicKey}/ota';
};

export type GetGearOtaErrors = {
    /**
     * Gear or firmware not found
     */
    404: ErrorResponse;
};

export type GetGearOtaError = GetGearOtaErrors[keyof GetGearOtaErrors];

export type GetGearOtaResponses = {
    /**
     * OTA summary
     */
    200: OtaSummary;
};

export type GetGearOtaResponse = GetGearOtaResponses[keyof GetGearOtaResponses];
