// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Channel = string;

export type Depot = {
    name: string;
    info: DepotInfo;
    rollback: DepotRelease;
    stable: DepotRelease;
    beta: DepotRelease;
    testing: DepotRelease;
};

export type DepotList = {
    items: Array<Depot>;
};

export type DepotInfo = {
    files?: Array<DepotInfoFile>;
};

export type DepotInfoFile = {
    path: string;
};

export type DepotRelease = {
    firmware_semver: string;
    channel?: string;
    files?: Array<DepotFile>;
};

export type DepotFile = {
    path: string;
    sha256: string;
    md5: string;
};

export type ErrorResponse = {
    error: ErrorPayload;
};

export type ErrorPayload = {
    code: string;
    message: string;
    details?: {
        [key: string]: unknown;
    };
};

/**
 * Firmware depot name
 */
export type DepotName = string;

/**
 * Release channel
 */
export type Channel2 = Channel;

export type ListDepotsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/firmwares';
};

export type ListDepotsErrors = {
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type ListDepotsError = ListDepotsErrors[keyof ListDepotsErrors];

export type ListDepotsResponses = {
    /**
     * Depot list
     */
    200: DepotList;
};

export type ListDepotsResponse = ListDepotsResponses[keyof ListDepotsResponses];

export type GetDepotData = {
    body?: never;
    path: {
        /**
         * Firmware depot name
         */
        depot: string;
    };
    query?: never;
    url: '/firmwares/{depot}';
};

export type GetDepotErrors = {
    /**
     * Depot not found
     */
    404: ErrorResponse;
};

export type GetDepotError = GetDepotErrors[keyof GetDepotErrors];

export type GetDepotResponses = {
    /**
     * Depot snapshot
     */
    200: Depot;
};

export type GetDepotResponse = GetDepotResponses[keyof GetDepotResponses];

export type PutDepotInfoData = {
    body: DepotInfo;
    path: {
        /**
         * Firmware depot name
         */
        depot: string;
    };
    query?: never;
    url: '/firmwares/{depot}';
};

export type PutDepotInfoErrors = {
    /**
     * Invalid JSON
     */
    400: ErrorResponse;
    /**
     * Info conflicts with existing releases
     */
    409: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type PutDepotInfoError = PutDepotInfoErrors[keyof PutDepotInfoErrors];

export type PutDepotInfoResponses = {
    /**
     * Updated depot snapshot
     */
    200: Depot;
};

export type PutDepotInfoResponse = PutDepotInfoResponses[keyof PutDepotInfoResponses];

export type ReleaseDepotData = {
    body?: never;
    path: {
        /**
         * Firmware depot name
         */
        depot: string;
    };
    query?: never;
    url: '/firmwares/{depot}/@release';
};

export type ReleaseDepotErrors = {
    /**
     * Depot not found
     */
    404: ErrorResponse;
    /**
     * Release not ready (testing channel missing)
     */
    409: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type ReleaseDepotError = ReleaseDepotErrors[keyof ReleaseDepotErrors];

export type ReleaseDepotResponses = {
    /**
     * Updated depot snapshot after release
     */
    200: Depot;
};

export type ReleaseDepotResponse = ReleaseDepotResponses[keyof ReleaseDepotResponses];

export type RollbackDepotData = {
    body?: never;
    path: {
        /**
         * Firmware depot name
         */
        depot: string;
    };
    query?: never;
    url: '/firmwares/{depot}/@rollback';
};

export type RollbackDepotErrors = {
    /**
     * Depot not found
     */
    404: ErrorResponse;
    /**
     * Rollback not available
     */
    409: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type RollbackDepotError = RollbackDepotErrors[keyof RollbackDepotErrors];

export type RollbackDepotResponses = {
    /**
     * Updated depot snapshot after rollback
     */
    200: Depot;
};

export type RollbackDepotResponse = RollbackDepotResponses[keyof RollbackDepotResponses];

export type GetChannelData = {
    body?: never;
    path: {
        /**
         * Firmware depot name
         */
        depot: string;
        /**
         * Release channel
         */
        channel: Channel;
    };
    query?: never;
    url: '/firmwares/{depot}/{channel}';
};

export type GetChannelErrors = {
    /**
     * Depot or channel not found
     */
    404: ErrorResponse;
};

export type GetChannelError = GetChannelErrors[keyof GetChannelErrors];

export type GetChannelResponses = {
    /**
     * Channel release
     */
    200: DepotRelease;
};

export type GetChannelResponse = GetChannelResponses[keyof GetChannelResponses];

export type PutChannelData = {
    body: Blob | File;
    path: {
        /**
         * Firmware depot name
         */
        depot: string;
        /**
         * Release channel
         */
        channel: Channel;
    };
    query?: never;
    url: '/firmwares/{depot}/{channel}';
};

export type PutChannelErrors = {
    /**
     * Invalid manifest in tarball
     */
    409: ErrorResponse;
};

export type PutChannelError = PutChannelErrors[keyof PutChannelErrors];

export type PutChannelResponses = {
    /**
     * Uploaded release
     */
    200: DepotRelease;
};

export type PutChannelResponse = PutChannelResponses[keyof PutChannelResponses];
