// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type DepotList = {
    items: Array<Depot>;
};

export type RegistrationList = {
    has_next: boolean;
    next_cursor?: string | null;
    items: Array<Registration>;
};

export type RefreshResult = {
    gear: Gear;
    updated_fields?: Array<string>;
    errors?: Array<string>;
};

export type PublicKeyResponse = {
    public_key: string;
};

export type ApproveRequest = {
    role: GearRole;
};

export type CredentialUpsert = {
    name: CredentialName;
    provider: CredentialProvider;
    method: CredentialMethod;
    description?: string;
    body: CredentialBody;
};

export type CredentialList = {
    has_next: boolean;
    next_cursor?: string | null;
    items: Array<Credential>;
};

export type MiniMaxTenantUpsert = {
    name: MiniMaxTenantName;
    app_id: MiniMaxAppId;
    group_id: MiniMaxGroupId;
    credential_name: CredentialName;
    base_url?: string;
    description?: string;
};

export type MiniMaxTenantList = {
    has_next: boolean;
    next_cursor?: string | null;
    items: Array<MiniMaxTenant>;
};

export type VoiceList = {
    has_next: boolean;
    next_cursor?: string | null;
    items: Array<Voice>;
};

export type VoiceUpsert = {
    id: VoiceId;
    source: VoiceSource;
    provider: VoiceProvider;
    /**
     * Upstream provider voice identifier. Present for synced voices.
     */
    provider_voice_id?: string;
    name?: string;
    description?: string;
    /**
     * Provider-specific voice type
     */
    provider_voice_type?: string;
    raw?: {
        [key: string]: unknown;
    };
};

export type MiniMaxSyncVoicesResult = {
    tenant_name: MiniMaxTenantName;
    synced_at: string;
    created_count: number;
    updated_count: number;
    deleted_count: number;
};

export type WorkspaceUpsert = {
    name: WorkspaceName;
    workspace_template_name: WorkspaceTemplateName;
    parameters?: {
        [key: string]: unknown;
    };
};

export type WorkspaceList = {
    has_next: boolean;
    next_cursor?: string | null;
    items: Array<Workspace>;
};

export type WorkspaceTemplateList = {
    has_next: boolean;
    next_cursor?: string | null;
    items: Array<WorkflowTemplateDocument>;
};

export type CredentialResource = {
    apiVersion: ResourceApiVersion;
    kind: 'Credential';
    metadata: ResourceMetadata;
    spec: CredentialSpec;
};

export type GearConfigResource = {
    apiVersion: ResourceApiVersion;
    kind: 'GearConfig';
    metadata: ResourceMetadata;
    spec: Configuration;
};

export type MiniMaxTenantResource = {
    apiVersion: ResourceApiVersion;
    kind: 'MiniMaxTenant';
    metadata: ResourceMetadata;
    spec: MiniMaxTenantSpec;
};

/**
 * Result of applying the resource.
 */
export type ApplyAction = 'created' | 'updated' | 'unchanged' | 'applied';

export type ApplyResult = {
    apiVersion: ResourceApiVersion;
    kind: ResourceKind;
    name: string;
    action: ApplyAction;
    message?: string;
    /**
     * Nested apply results for ResourceList resources.
     */
    items?: Array<ApplyResult>;
};

export type Resource = ({
    kind: 'CredentialResource';
} & CredentialResource) | ({
    kind: 'MiniMaxTenantResource';
} & MiniMaxTenantResource) | ({
    kind: 'VoiceResource';
} & VoiceResource) | ({
    kind: 'WorkspaceTemplateResource';
} & WorkspaceTemplateResource) | ({
    kind: 'WorkspaceResource';
} & WorkspaceResource) | ({
    kind: 'GearConfigResource';
} & GearConfigResource) | ({
    kind: 'ResourceListResource';
} & ResourceListResource);

/**
 * API version for declarative GizClaw resources.
 */
export type ResourceApiVersion = 'gizclaw.admin/v1alpha1';

/**
 * Declarative GizClaw resource kind.
 */
export type ResourceKind = 'Credential' | 'MiniMaxTenant' | 'Voice' | 'WorkspaceTemplate' | 'Workspace' | 'GearConfig' | 'ResourceList';

export type ResourceMetadata = {
    /**
     * Resource name. For GearConfig this is the gear public key.
     */
    name: string;
    annotations?: {
        [key: string]: string;
    };
    labels?: {
        [key: string]: string;
    };
};

export type ResourceListResource = {
    apiVersion: ResourceApiVersion;
    kind: 'ResourceList';
    metadata: ResourceMetadata;
    spec: ResourceListSpec;
};

export type VoiceResource = {
    apiVersion: ResourceApiVersion;
    kind: 'Voice';
    metadata: ResourceMetadata;
    spec: VoiceSpec;
};

export type WorkspaceResource = {
    apiVersion: ResourceApiVersion;
    kind: 'Workspace';
    metadata: ResourceMetadata;
    spec: WorkspaceSpec;
};

export type WorkspaceTemplateResource = {
    apiVersion: ResourceApiVersion;
    kind: 'WorkspaceTemplate';
    metadata: ResourceMetadata;
    spec: WorkflowTemplateDocument;
};

export type Channel = string;

export type Configuration = {
    certifications?: Array<GearCertification>;
    firmware?: FirmwareConfig;
};

export type Credential = {
    name: CredentialName;
    provider: CredentialProvider;
    method: CredentialMethod;
    body: CredentialBody;
    description?: string;
    created_at: string;
    updated_at: string;
};

export type CredentialBody = {
    [key: string]: unknown;
};

/**
 * Credential authentication method
 */
export type CredentialMethod = 'api_key' | 'token' | 'app_id_token';

/**
 * Credential name
 */
export type CredentialName = string;

/**
 * Credential provider name
 */
export type CredentialProvider = string;

export type CredentialSpec = {
    provider: CredentialProvider;
    method: CredentialMethod;
    description?: string;
    body: CredentialBody;
};

export type Depot = {
    name: string;
    info: DepotInfo;
    rollback: DepotRelease;
    stable: DepotRelease;
    beta: DepotRelease;
    testing: DepotRelease;
};

export type DepotFile = {
    path: string;
    sha256: string;
    md5: string;
};

export type DepotInfo = {
    files?: Array<DepotInfoFile>;
};

export type DepotInfoFile = {
    path: string;
};

export type DepotRelease = {
    firmware_semver: string;
    channel?: string;
    files?: Array<DepotFile>;
};

export type DeviceInfo = {
    name?: string;
    sn?: string;
    hardware?: HardwareInfo;
};

export type ErrorPayload = {
    code: string;
    message: string;
    details?: {
        [key: string]: unknown;
    };
};

export type ErrorResponse = {
    error: ErrorPayload;
};

export type FirmwareConfig = {
    channel?: GearFirmwareChannel;
};

export type Gear = {
    public_key: string;
    role: GearRole;
    status: GearStatus;
    device: DeviceInfo;
    configuration: Configuration;
    auto_registered?: boolean;
    created_at: string;
    updated_at: string;
    approved_at?: string;
};

export type GearCertification = {
    type: GearCertificationType;
    authority: GearCertificationAuthority;
    id: string;
    authority_name?: string;
};

export type GearCertificationAuthority = 'unknown' | 'ccc' | 'ce' | 'fcc' | 'miit' | 'srrc' | 'rohs' | 'internal';

export type GearCertificationType = 'license' | 'certification';

export type GearFirmwareChannel = string;

export type GearImei = {
    name?: string;
    tac: string;
    serial: string;
};

export type GearLabel = {
    key: string;
    value: string;
};

export type GearRole = 'unspecified' | 'admin' | 'server' | 'gear';

export type GearStatus = 'unspecified' | 'active' | 'blocked';

export type HardwareInfo = {
    manufacturer?: string;
    model?: string;
    hardware_revision?: string;
    depot?: string;
    firmware_semver?: string;
    imeis?: Array<GearImei>;
    labels?: Array<GearLabel>;
};

/**
 * MiniMax app identifier
 */
export type MiniMaxAppId = string;

/**
 * MiniMax group identifier
 */
export type MiniMaxGroupId = string;

export type MiniMaxTenant = {
    name: MiniMaxTenantName;
    app_id: MiniMaxAppId;
    group_id: MiniMaxGroupId;
    credential_name: CredentialName;
    base_url?: string;
    description?: string;
    last_synced_at?: string;
    created_at: string;
    updated_at: string;
};

/**
 * MiniMax tenant name
 */
export type MiniMaxTenantName = string;

export type MiniMaxTenantSpec = {
    app_id: MiniMaxAppId;
    group_id: MiniMaxGroupId;
    credential_name: CredentialName;
    base_url?: string;
    description?: string;
};

export type MultiAgentGraphWorkflowSpec = {
    [key: string]: unknown;
};

export type MultiAgentGraphWorkflowTemplate = {
    apiVersion: WorkflowTemplateApiVersion;
    kind: 'MultiAgentGraphWorkflowTemplate';
    metadata: TemplateMetadata;
    spec: MultiAgentGraphWorkflowSpec;
};

export type OtaSummary = {
    depot: string;
    channel: string;
    firmware_semver: string;
    files: Array<DepotFile>;
};

export type Registration = {
    public_key: string;
    role: GearRole;
    status: GearStatus;
    auto_registered?: boolean;
    created_at: string;
    updated_at: string;
    approved_at?: string;
};

export type ResourceListSpec = {
    items: Array<Resource>;
};

export type Runtime = {
    online: boolean;
    last_seen_at: string;
    last_addr?: string;
};

export type SingleAgentGraphWorkflowSpec = {
    [key: string]: unknown;
};

export type SingleAgentGraphWorkflowTemplate = {
    apiVersion: WorkflowTemplateApiVersion;
    kind: 'SingleAgentGraphWorkflowTemplate';
    metadata: TemplateMetadata;
    spec: SingleAgentGraphWorkflowSpec;
};

export type TemplateMetadata = {
    name: string;
    description?: string;
};

export type Voice = {
    id: VoiceId;
    source: VoiceSource;
    provider: VoiceProvider;
    /**
     * Upstream provider voice identifier. Present for synced voices.
     */
    provider_voice_id?: string;
    name?: string;
    description?: string;
    /**
     * Provider-specific voice type
     */
    provider_voice_type?: string;
    raw?: {
        [key: string]: unknown;
    };
    synced_at?: string;
    created_at: string;
    updated_at: string;
};

/**
 * Global voice identifier
 */
export type VoiceId = string;

export type VoiceProvider = {
    kind: VoiceProviderKind;
    name: VoiceProviderName;
};

/**
 * Voice provider kind
 */
export type VoiceProviderKind = string;

/**
 * Voice provider instance name
 */
export type VoiceProviderName = string;

/**
 * How the voice entered the global catalog
 */
export type VoiceSource = 'sync' | 'manual';

export type VoiceSpec = {
    source: VoiceSource;
    provider: VoiceProvider;
    /**
     * Upstream provider voice identifier. Present for synced voices.
     */
    provider_voice_id?: string;
    name?: string;
    description?: string;
    /**
     * Provider-specific voice type
     */
    provider_voice_type?: string;
    raw?: {
        [key: string]: unknown;
    };
};

export type WorkflowTemplateApiVersion = 'gizclaw.flowcraft/v1alpha1';

export type WorkflowTemplateDocument = ({
    kind: 'SingleAgentGraphWorkflowTemplate';
} & SingleAgentGraphWorkflowTemplate) | ({
    kind: 'MultiAgentGraphWorkflowTemplate';
} & MultiAgentGraphWorkflowTemplate);

export type Workspace = {
    name: WorkspaceName;
    workspace_template_name: WorkspaceTemplateName;
    parameters?: {
        [key: string]: unknown;
    };
    created_at: string;
    updated_at: string;
};

/**
 * Workspace name
 */
export type WorkspaceName = string;

export type WorkspaceSpec = {
    workspace_template_name: WorkspaceTemplateName;
    parameters?: {
        [key: string]: unknown;
    };
};

/**
 * Workspace template name
 */
export type WorkspaceTemplateName = string;

/**
 * Opaque cursor returned by the previous list response
 */
export type Cursor = string;

/**
 * Maximum number of items to return. Omitted or non-positive values use the default page size; values above 200 are clamped.
 */
export type Limit = number;

/**
 * Firmware depot name
 */
export type DepotName = string;

/**
 * Release channel
 */
export type Channel2 = Channel;

/**
 * Gear public key
 */
export type PublicKey = string;

/**
 * Workspace template name
 */
export type WorkspaceTemplateName2 = WorkspaceTemplateName;

/**
 * Workspace name
 */
export type WorkspaceName2 = WorkspaceName;

/**
 * Credential name
 */
export type CredentialName2 = CredentialName;

/**
 * Filter credentials by provider
 */
export type CredentialProvider2 = CredentialProvider;

/**
 * Declarative resource kind
 */
export type ResourceKind2 = ResourceKind;

/**
 * Declarative resource metadata.name
 */
export type ResourceName = string;

/**
 * MiniMax tenant name
 */
export type MiniMaxTenantName2 = MiniMaxTenantName;

/**
 * Voice identifier
 */
export type VoiceId2 = VoiceId;

/**
 * Filter voices by source
 */
export type VoiceSource2 = VoiceSource;

/**
 * Filter voices by provider kind
 */
export type VoiceProviderKind2 = VoiceProviderKind;

/**
 * Filter voices by provider instance name
 */
export type VoiceProviderName2 = VoiceProviderName;

export type ApplyResourceData = {
    body: Resource;
    path?: never;
    query?: never;
    url: '/@apply';
};

export type ApplyResourceErrors = {
    /**
     * Invalid apply resource
     */
    400: ErrorResponse;
    /**
     * Resource conflict
     */
    409: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
    /**
     * Apply is defined but not implemented
     */
    501: ErrorResponse;
};

export type ApplyResourceError = ApplyResourceErrors[keyof ApplyResourceErrors];

export type ApplyResourceResponses = {
    /**
     * Applied resource result
     */
    200: ApplyResult;
};

export type ApplyResourceResponse = ApplyResourceResponses[keyof ApplyResourceResponses];

export type DeleteResourceData = {
    body?: never;
    path: {
        /**
         * Declarative resource kind
         */
        kind: ResourceKind;
        /**
         * Declarative resource metadata.name
         */
        name: string;
    };
    query?: never;
    url: '/resources/{kind}/{name}';
};

export type DeleteResourceErrors = {
    /**
     * Invalid or unsupported resource delete
     */
    400: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
    /**
     * Resource conflict
     */
    409: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type DeleteResourceError = DeleteResourceErrors[keyof DeleteResourceErrors];

export type DeleteResourceResponses = {
    /**
     * Deleted declarative resource
     */
    200: Resource;
};

export type DeleteResourceResponse = DeleteResourceResponses[keyof DeleteResourceResponses];

export type GetResourceData = {
    body?: never;
    path: {
        /**
         * Declarative resource kind
         */
        kind: ResourceKind;
        /**
         * Declarative resource metadata.name
         */
        name: string;
    };
    query?: never;
    url: '/resources/{kind}/{name}';
};

export type GetResourceErrors = {
    /**
     * Invalid resource kind or name
     */
    400: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
    /**
     * Resource get is defined but not implemented
     */
    501: ErrorResponse;
};

export type GetResourceError = GetResourceErrors[keyof GetResourceErrors];

export type GetResourceResponses = {
    /**
     * Declarative resource
     */
    200: Resource;
};

export type GetResourceResponse = GetResourceResponses[keyof GetResourceResponses];

export type PutResourceData = {
    body: Resource;
    path: {
        /**
         * Declarative resource kind
         */
        kind: ResourceKind;
        /**
         * Declarative resource metadata.name
         */
        name: string;
    };
    query?: never;
    url: '/resources/{kind}/{name}';
};

export type PutResourceErrors = {
    /**
     * Invalid resource
     */
    400: ErrorResponse;
    /**
     * Backing resource not found
     */
    404: ErrorResponse;
    /**
     * Resource conflict
     */
    409: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
    /**
     * Resource put is defined but not implemented
     */
    501: ErrorResponse;
};

export type PutResourceError = PutResourceErrors[keyof PutResourceErrors];

export type PutResourceResponses = {
    /**
     * Stored declarative resource
     */
    200: Resource;
};

export type PutResourceResponse = PutResourceResponses[keyof PutResourceResponses];

export type ListDepotsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/depots';
};

export type ListDepotsErrors = {
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type ListDepotsError = ListDepotsErrors[keyof ListDepotsErrors];

export type ListDepotsResponses = {
    /**
     * Depot list
     */
    200: DepotList;
};

export type ListDepotsResponse = ListDepotsResponses[keyof ListDepotsResponses];

export type GetDepotData = {
    body?: never;
    path: {
        /**
         * Firmware depot name
         */
        depot: string;
    };
    query?: never;
    url: '/depots/{depot}';
};

export type GetDepotErrors = {
    /**
     * Depot not found
     */
    404: ErrorResponse;
};

export type GetDepotError = GetDepotErrors[keyof GetDepotErrors];

export type GetDepotResponses = {
    /**
     * Depot snapshot
     */
    200: Depot;
};

export type GetDepotResponse = GetDepotResponses[keyof GetDepotResponses];

export type PutDepotInfoData = {
    body: DepotInfo;
    path: {
        /**
         * Firmware depot name
         */
        depot: string;
    };
    query?: never;
    url: '/depots/{depot}';
};

export type PutDepotInfoErrors = {
    /**
     * Invalid JSON
     */
    400: ErrorResponse;
    /**
     * Info conflicts with existing releases
     */
    409: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type PutDepotInfoError = PutDepotInfoErrors[keyof PutDepotInfoErrors];

export type PutDepotInfoResponses = {
    /**
     * Updated depot snapshot
     */
    200: Depot;
};

export type PutDepotInfoResponse = PutDepotInfoResponses[keyof PutDepotInfoResponses];

export type ReleaseDepotData = {
    body?: never;
    path: {
        /**
         * Firmware depot name
         */
        depot: string;
    };
    query?: never;
    url: '/depots/{depot}/@release';
};

export type ReleaseDepotErrors = {
    /**
     * Depot not found
     */
    404: ErrorResponse;
    /**
     * Release not ready (testing channel missing)
     */
    409: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type ReleaseDepotError = ReleaseDepotErrors[keyof ReleaseDepotErrors];

export type ReleaseDepotResponses = {
    /**
     * Updated depot snapshot after release
     */
    200: Depot;
};

export type ReleaseDepotResponse = ReleaseDepotResponses[keyof ReleaseDepotResponses];

export type RollbackDepotData = {
    body?: never;
    path: {
        /**
         * Firmware depot name
         */
        depot: string;
    };
    query?: never;
    url: '/depots/{depot}/@rollback';
};

export type RollbackDepotErrors = {
    /**
     * Depot not found
     */
    404: ErrorResponse;
    /**
     * Rollback not available
     */
    409: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type RollbackDepotError = RollbackDepotErrors[keyof RollbackDepotErrors];

export type RollbackDepotResponses = {
    /**
     * Updated depot snapshot after rollback
     */
    200: Depot;
};

export type RollbackDepotResponse = RollbackDepotResponses[keyof RollbackDepotResponses];

export type GetChannelData = {
    body?: never;
    path: {
        /**
         * Firmware depot name
         */
        depot: string;
        /**
         * Release channel
         */
        channel: Channel;
    };
    query?: never;
    url: '/depots/{depot}/channels/{channel}';
};

export type GetChannelErrors = {
    /**
     * Depot or channel not found
     */
    404: ErrorResponse;
};

export type GetChannelError = GetChannelErrors[keyof GetChannelErrors];

export type GetChannelResponses = {
    /**
     * Channel release
     */
    200: DepotRelease;
};

export type GetChannelResponse = GetChannelResponses[keyof GetChannelResponses];

export type PutChannelData = {
    body: Blob | File;
    path: {
        /**
         * Firmware depot name
         */
        depot: string;
        /**
         * Release channel
         */
        channel: Channel;
    };
    query?: never;
    url: '/depots/{depot}/channels/{channel}';
};

export type PutChannelErrors = {
    /**
     * Invalid manifest in tarball
     */
    409: ErrorResponse;
};

export type PutChannelError = PutChannelErrors[keyof PutChannelErrors];

export type PutChannelResponses = {
    /**
     * Uploaded release
     */
    200: DepotRelease;
};

export type PutChannelResponse = PutChannelResponses[keyof PutChannelResponses];

export type ListWorkspaceTemplatesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Opaque cursor returned by the previous list response
         */
        cursor?: string;
        /**
         * Maximum number of items to return. Omitted or non-positive values use the default page size; values above 200 are clamped.
         */
        limit?: number;
    };
    url: '/workspace-templates';
};

export type ListWorkspaceTemplatesErrors = {
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type ListWorkspaceTemplatesError = ListWorkspaceTemplatesErrors[keyof ListWorkspaceTemplatesErrors];

export type ListWorkspaceTemplatesResponses = {
    /**
     * Workspace template list
     */
    200: WorkspaceTemplateList;
};

export type ListWorkspaceTemplatesResponse = ListWorkspaceTemplatesResponses[keyof ListWorkspaceTemplatesResponses];

export type CreateWorkspaceTemplateData = {
    body: WorkflowTemplateDocument;
    path?: never;
    query?: never;
    url: '/workspace-templates';
};

export type CreateWorkspaceTemplateErrors = {
    /**
     * Invalid template payload
     */
    400: ErrorResponse;
    /**
     * Template already exists
     */
    409: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type CreateWorkspaceTemplateError = CreateWorkspaceTemplateErrors[keyof CreateWorkspaceTemplateErrors];

export type CreateWorkspaceTemplateResponses = {
    /**
     * Created workspace template
     */
    200: WorkflowTemplateDocument;
};

export type CreateWorkspaceTemplateResponse = CreateWorkspaceTemplateResponses[keyof CreateWorkspaceTemplateResponses];

export type ListCredentialsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter credentials by provider
         */
        provider?: CredentialProvider;
        /**
         * Opaque cursor returned by the previous list response
         */
        cursor?: string;
        /**
         * Maximum number of items to return. Omitted or non-positive values use the default page size; values above 200 are clamped.
         */
        limit?: number;
    };
    url: '/credentials';
};

export type ListCredentialsErrors = {
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type ListCredentialsError = ListCredentialsErrors[keyof ListCredentialsErrors];

export type ListCredentialsResponses = {
    /**
     * Credential list
     */
    200: CredentialList;
};

export type ListCredentialsResponse = ListCredentialsResponses[keyof ListCredentialsResponses];

export type CreateCredentialData = {
    body: CredentialUpsert;
    path?: never;
    query?: never;
    url: '/credentials';
};

export type CreateCredentialErrors = {
    /**
     * Invalid credential payload
     */
    400: ErrorResponse;
    /**
     * Credential already exists
     */
    409: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type CreateCredentialError = CreateCredentialErrors[keyof CreateCredentialErrors];

export type CreateCredentialResponses = {
    /**
     * Created credential
     */
    200: Credential;
};

export type CreateCredentialResponse = CreateCredentialResponses[keyof CreateCredentialResponses];

export type DeleteCredentialData = {
    body?: never;
    path: {
        /**
         * Credential name
         */
        name: CredentialName;
    };
    query?: never;
    url: '/credentials/{name}';
};

export type DeleteCredentialErrors = {
    /**
     * Credential not found
     */
    404: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type DeleteCredentialError = DeleteCredentialErrors[keyof DeleteCredentialErrors];

export type DeleteCredentialResponses = {
    /**
     * Deleted credential
     */
    200: Credential;
};

export type DeleteCredentialResponse = DeleteCredentialResponses[keyof DeleteCredentialResponses];

export type GetCredentialData = {
    body?: never;
    path: {
        /**
         * Credential name
         */
        name: CredentialName;
    };
    query?: never;
    url: '/credentials/{name}';
};

export type GetCredentialErrors = {
    /**
     * Credential not found
     */
    404: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type GetCredentialError = GetCredentialErrors[keyof GetCredentialErrors];

export type GetCredentialResponses = {
    /**
     * Credential metadata
     */
    200: Credential;
};

export type GetCredentialResponse = GetCredentialResponses[keyof GetCredentialResponses];

export type PutCredentialData = {
    body: CredentialUpsert;
    path: {
        /**
         * Credential name
         */
        name: CredentialName;
    };
    query?: never;
    url: '/credentials/{name}';
};

export type PutCredentialErrors = {
    /**
     * Invalid credential payload
     */
    400: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type PutCredentialError = PutCredentialErrors[keyof PutCredentialErrors];

export type PutCredentialResponses = {
    /**
     * Stored credential
     */
    200: Credential;
};

export type PutCredentialResponse = PutCredentialResponses[keyof PutCredentialResponses];

export type ListMiniMaxTenantsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Opaque cursor returned by the previous list response
         */
        cursor?: string;
        /**
         * Maximum number of items to return. Omitted or non-positive values use the default page size; values above 200 are clamped.
         */
        limit?: number;
    };
    url: '/minimax-tenants';
};

export type ListMiniMaxTenantsErrors = {
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type ListMiniMaxTenantsError = ListMiniMaxTenantsErrors[keyof ListMiniMaxTenantsErrors];

export type ListMiniMaxTenantsResponses = {
    /**
     * MiniMax tenant list
     */
    200: MiniMaxTenantList;
};

export type ListMiniMaxTenantsResponse = ListMiniMaxTenantsResponses[keyof ListMiniMaxTenantsResponses];

export type CreateMiniMaxTenantData = {
    body: MiniMaxTenantUpsert;
    path?: never;
    query?: never;
    url: '/minimax-tenants';
};

export type CreateMiniMaxTenantErrors = {
    /**
     * Invalid MiniMax tenant payload
     */
    400: ErrorResponse;
    /**
     * MiniMax tenant already exists
     */
    409: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type CreateMiniMaxTenantError = CreateMiniMaxTenantErrors[keyof CreateMiniMaxTenantErrors];

export type CreateMiniMaxTenantResponses = {
    /**
     * Created MiniMax tenant
     */
    200: MiniMaxTenant;
};

export type CreateMiniMaxTenantResponse = CreateMiniMaxTenantResponses[keyof CreateMiniMaxTenantResponses];

export type DeleteMiniMaxTenantData = {
    body?: never;
    path: {
        /**
         * MiniMax tenant name
         */
        name: MiniMaxTenantName;
    };
    query?: never;
    url: '/minimax-tenants/{name}';
};

export type DeleteMiniMaxTenantErrors = {
    /**
     * MiniMax tenant not found
     */
    404: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type DeleteMiniMaxTenantError = DeleteMiniMaxTenantErrors[keyof DeleteMiniMaxTenantErrors];

export type DeleteMiniMaxTenantResponses = {
    /**
     * Deleted MiniMax tenant
     */
    200: MiniMaxTenant;
};

export type DeleteMiniMaxTenantResponse = DeleteMiniMaxTenantResponses[keyof DeleteMiniMaxTenantResponses];

export type GetMiniMaxTenantData = {
    body?: never;
    path: {
        /**
         * MiniMax tenant name
         */
        name: MiniMaxTenantName;
    };
    query?: never;
    url: '/minimax-tenants/{name}';
};

export type GetMiniMaxTenantErrors = {
    /**
     * MiniMax tenant not found
     */
    404: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type GetMiniMaxTenantError = GetMiniMaxTenantErrors[keyof GetMiniMaxTenantErrors];

export type GetMiniMaxTenantResponses = {
    /**
     * MiniMax tenant
     */
    200: MiniMaxTenant;
};

export type GetMiniMaxTenantResponse = GetMiniMaxTenantResponses[keyof GetMiniMaxTenantResponses];

export type PutMiniMaxTenantData = {
    body: MiniMaxTenantUpsert;
    path: {
        /**
         * MiniMax tenant name
         */
        name: MiniMaxTenantName;
    };
    query?: never;
    url: '/minimax-tenants/{name}';
};

export type PutMiniMaxTenantErrors = {
    /**
     * Invalid MiniMax tenant payload
     */
    400: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type PutMiniMaxTenantError = PutMiniMaxTenantErrors[keyof PutMiniMaxTenantErrors];

export type PutMiniMaxTenantResponses = {
    /**
     * Stored MiniMax tenant
     */
    200: MiniMaxTenant;
};

export type PutMiniMaxTenantResponse = PutMiniMaxTenantResponses[keyof PutMiniMaxTenantResponses];

export type SyncMiniMaxTenantVoicesData = {
    body?: never;
    path: {
        /**
         * MiniMax tenant name
         */
        name: MiniMaxTenantName;
    };
    query?: never;
    url: '/minimax-tenants/{name}/@sync-voices';
};

export type SyncMiniMaxTenantVoicesErrors = {
    /**
     * Invalid MiniMax tenant configuration
     */
    400: ErrorResponse;
    /**
     * MiniMax tenant not found
     */
    404: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
    /**
     * Upstream MiniMax sync failed
     */
    502: ErrorResponse;
};

export type SyncMiniMaxTenantVoicesError = SyncMiniMaxTenantVoicesErrors[keyof SyncMiniMaxTenantVoicesErrors];

export type SyncMiniMaxTenantVoicesResponses = {
    /**
     * MiniMax voice sync result
     */
    200: MiniMaxSyncVoicesResult;
};

export type SyncMiniMaxTenantVoicesResponse = SyncMiniMaxTenantVoicesResponses[keyof SyncMiniMaxTenantVoicesResponses];

export type ListVoicesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter voices by source
         */
        source?: VoiceSource;
        /**
         * Filter voices by provider kind
         */
        providerKind?: VoiceProviderKind;
        /**
         * Filter voices by provider instance name
         */
        providerName?: VoiceProviderName;
        /**
         * Opaque cursor returned by the previous list response
         */
        cursor?: string;
        /**
         * Maximum number of items to return. Omitted or non-positive values use the default page size; values above 200 are clamped.
         */
        limit?: number;
    };
    url: '/voices';
};

export type ListVoicesErrors = {
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type ListVoicesError = ListVoicesErrors[keyof ListVoicesErrors];

export type ListVoicesResponses = {
    /**
     * Voice list
     */
    200: VoiceList;
};

export type ListVoicesResponse = ListVoicesResponses[keyof ListVoicesResponses];

export type CreateVoiceData = {
    body: VoiceUpsert;
    path?: never;
    query?: never;
    url: '/voices';
};

export type CreateVoiceErrors = {
    /**
     * Invalid voice payload
     */
    400: ErrorResponse;
    /**
     * Voice already exists
     */
    409: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type CreateVoiceError = CreateVoiceErrors[keyof CreateVoiceErrors];

export type CreateVoiceResponses = {
    /**
     * Created voice
     */
    200: Voice;
};

export type CreateVoiceResponse = CreateVoiceResponses[keyof CreateVoiceResponses];

export type DeleteVoiceData = {
    body?: never;
    path: {
        /**
         * Voice identifier
         */
        id: VoiceId;
    };
    query?: never;
    url: '/voices/{id}';
};

export type DeleteVoiceErrors = {
    /**
     * Voice not found
     */
    404: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type DeleteVoiceError = DeleteVoiceErrors[keyof DeleteVoiceErrors];

export type DeleteVoiceResponses = {
    /**
     * Deleted voice
     */
    200: Voice;
};

export type DeleteVoiceResponse = DeleteVoiceResponses[keyof DeleteVoiceResponses];

export type GetVoiceData = {
    body?: never;
    path: {
        /**
         * Voice identifier
         */
        id: VoiceId;
    };
    query?: never;
    url: '/voices/{id}';
};

export type GetVoiceErrors = {
    /**
     * Voice not found
     */
    404: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type GetVoiceError = GetVoiceErrors[keyof GetVoiceErrors];

export type GetVoiceResponses = {
    /**
     * Voice
     */
    200: Voice;
};

export type GetVoiceResponse = GetVoiceResponses[keyof GetVoiceResponses];

export type PutVoiceData = {
    body: VoiceUpsert;
    path: {
        /**
         * Voice identifier
         */
        id: VoiceId;
    };
    query?: never;
    url: '/voices/{id}';
};

export type PutVoiceErrors = {
    /**
     * Invalid voice payload
     */
    400: ErrorResponse;
    /**
     * Voice cannot be modified because source is sync
     */
    409: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type PutVoiceError = PutVoiceErrors[keyof PutVoiceErrors];

export type PutVoiceResponses = {
    /**
     * Stored voice
     */
    200: Voice;
};

export type PutVoiceResponse = PutVoiceResponses[keyof PutVoiceResponses];

export type DeleteWorkspaceTemplateData = {
    body?: never;
    path: {
        /**
         * Workspace template name
         */
        name: WorkspaceTemplateName;
    };
    query?: never;
    url: '/workspace-templates/{name}';
};

export type DeleteWorkspaceTemplateErrors = {
    /**
     * Workspace template not found
     */
    404: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type DeleteWorkspaceTemplateError = DeleteWorkspaceTemplateErrors[keyof DeleteWorkspaceTemplateErrors];

export type DeleteWorkspaceTemplateResponses = {
    /**
     * Deleted workspace template
     */
    200: WorkflowTemplateDocument;
};

export type DeleteWorkspaceTemplateResponse = DeleteWorkspaceTemplateResponses[keyof DeleteWorkspaceTemplateResponses];

export type GetWorkspaceTemplateData = {
    body?: never;
    path: {
        /**
         * Workspace template name
         */
        name: WorkspaceTemplateName;
    };
    query?: never;
    url: '/workspace-templates/{name}';
};

export type GetWorkspaceTemplateErrors = {
    /**
     * Workspace template not found
     */
    404: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type GetWorkspaceTemplateError = GetWorkspaceTemplateErrors[keyof GetWorkspaceTemplateErrors];

export type GetWorkspaceTemplateResponses = {
    /**
     * Workspace template document
     */
    200: WorkflowTemplateDocument;
};

export type GetWorkspaceTemplateResponse = GetWorkspaceTemplateResponses[keyof GetWorkspaceTemplateResponses];

export type PutWorkspaceTemplateData = {
    body: WorkflowTemplateDocument;
    path: {
        /**
         * Workspace template name
         */
        name: WorkspaceTemplateName;
    };
    query?: never;
    url: '/workspace-templates/{name}';
};

export type PutWorkspaceTemplateErrors = {
    /**
     * Invalid template payload
     */
    400: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type PutWorkspaceTemplateError = PutWorkspaceTemplateErrors[keyof PutWorkspaceTemplateErrors];

export type PutWorkspaceTemplateResponses = {
    /**
     * Stored workspace template
     */
    200: WorkflowTemplateDocument;
};

export type PutWorkspaceTemplateResponse = PutWorkspaceTemplateResponses[keyof PutWorkspaceTemplateResponses];

export type ListWorkspacesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Opaque cursor returned by the previous list response
         */
        cursor?: string;
        /**
         * Maximum number of items to return. Omitted or non-positive values use the default page size; values above 200 are clamped.
         */
        limit?: number;
    };
    url: '/workspaces';
};

export type ListWorkspacesErrors = {
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type ListWorkspacesError = ListWorkspacesErrors[keyof ListWorkspacesErrors];

export type ListWorkspacesResponses = {
    /**
     * Workspace list
     */
    200: WorkspaceList;
};

export type ListWorkspacesResponse = ListWorkspacesResponses[keyof ListWorkspacesResponses];

export type CreateWorkspaceData = {
    body: WorkspaceUpsert;
    path?: never;
    query?: never;
    url: '/workspaces';
};

export type CreateWorkspaceErrors = {
    /**
     * Invalid workspace payload
     */
    400: ErrorResponse;
    /**
     * Workspace already exists
     */
    409: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type CreateWorkspaceError = CreateWorkspaceErrors[keyof CreateWorkspaceErrors];

export type CreateWorkspaceResponses = {
    /**
     * Created workspace
     */
    200: Workspace;
};

export type CreateWorkspaceResponse = CreateWorkspaceResponses[keyof CreateWorkspaceResponses];

export type DeleteWorkspaceData = {
    body?: never;
    path: {
        /**
         * Workspace name
         */
        name: WorkspaceName;
    };
    query?: never;
    url: '/workspaces/{name}';
};

export type DeleteWorkspaceErrors = {
    /**
     * Workspace not found
     */
    404: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type DeleteWorkspaceError = DeleteWorkspaceErrors[keyof DeleteWorkspaceErrors];

export type DeleteWorkspaceResponses = {
    /**
     * Deleted workspace
     */
    200: Workspace;
};

export type DeleteWorkspaceResponse = DeleteWorkspaceResponses[keyof DeleteWorkspaceResponses];

export type GetWorkspaceData = {
    body?: never;
    path: {
        /**
         * Workspace name
         */
        name: WorkspaceName;
    };
    query?: never;
    url: '/workspaces/{name}';
};

export type GetWorkspaceErrors = {
    /**
     * Workspace not found
     */
    404: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type GetWorkspaceError = GetWorkspaceErrors[keyof GetWorkspaceErrors];

export type GetWorkspaceResponses = {
    /**
     * Workspace
     */
    200: Workspace;
};

export type GetWorkspaceResponse = GetWorkspaceResponses[keyof GetWorkspaceResponses];

export type PutWorkspaceData = {
    body: WorkspaceUpsert;
    path: {
        /**
         * Workspace name
         */
        name: WorkspaceName;
    };
    query?: never;
    url: '/workspaces/{name}';
};

export type PutWorkspaceErrors = {
    /**
     * Invalid workspace payload
     */
    400: ErrorResponse;
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type PutWorkspaceError = PutWorkspaceErrors[keyof PutWorkspaceErrors];

export type PutWorkspaceResponses = {
    /**
     * Stored workspace
     */
    200: Workspace;
};

export type PutWorkspaceResponse = PutWorkspaceResponses[keyof PutWorkspaceResponses];

export type ListGearsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Opaque cursor returned by the previous list response
         */
        cursor?: string;
        /**
         * Maximum number of items to return. Omitted or non-positive values use the default page size; values above 200 are clamped.
         */
        limit?: number;
    };
    url: '/gears';
};

export type ListGearsErrors = {
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type ListGearsError = ListGearsErrors[keyof ListGearsErrors];

export type ListGearsResponses = {
    /**
     * Gear registration list
     */
    200: RegistrationList;
};

export type ListGearsResponse = ListGearsResponses[keyof ListGearsResponses];

export type ResolveBySnData = {
    body?: never;
    path: {
        sn: string;
    };
    query?: never;
    url: '/gears/sn/{sn}';
};

export type ResolveBySnErrors = {
    /**
     * Gear not found
     */
    404: ErrorResponse;
};

export type ResolveBySnError = ResolveBySnErrors[keyof ResolveBySnErrors];

export type ResolveBySnResponses = {
    /**
     * Resolved public key
     */
    200: PublicKeyResponse;
};

export type ResolveBySnResponse = ResolveBySnResponses[keyof ResolveBySnResponses];

export type ResolveByImeiData = {
    body?: never;
    path: {
        tac: string;
        serial: string;
    };
    query?: never;
    url: '/gears/imei/{tac}/{serial}';
};

export type ResolveByImeiErrors = {
    /**
     * Gear not found
     */
    404: ErrorResponse;
};

export type ResolveByImeiError = ResolveByImeiErrors[keyof ResolveByImeiErrors];

export type ResolveByImeiResponses = {
    /**
     * Resolved public key
     */
    200: PublicKeyResponse;
};

export type ResolveByImeiResponse = ResolveByImeiResponses[keyof ResolveByImeiResponses];

export type ListByLabelData = {
    body?: never;
    path: {
        key: string;
        value: string;
    };
    query?: {
        /**
         * Opaque cursor returned by the previous list response
         */
        cursor?: string;
        /**
         * Maximum number of items to return. Omitted or non-positive values use the default page size; values above 200 are clamped.
         */
        limit?: number;
    };
    url: '/gears/label/{key}/{value}';
};

export type ListByLabelErrors = {
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type ListByLabelError = ListByLabelErrors[keyof ListByLabelErrors];

export type ListByLabelResponses = {
    /**
     * Matched gears
     */
    200: RegistrationList;
};

export type ListByLabelResponse = ListByLabelResponses[keyof ListByLabelResponses];

export type ListByCertificationData = {
    body?: never;
    path: {
        type: GearCertificationType;
        authority: GearCertificationAuthority;
        id: string;
    };
    query?: {
        /**
         * Opaque cursor returned by the previous list response
         */
        cursor?: string;
        /**
         * Maximum number of items to return. Omitted or non-positive values use the default page size; values above 200 are clamped.
         */
        limit?: number;
    };
    url: '/gears/certification/{type}/{authority}/{id}';
};

export type ListByCertificationErrors = {
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type ListByCertificationError = ListByCertificationErrors[keyof ListByCertificationErrors];

export type ListByCertificationResponses = {
    /**
     * Matched gears
     */
    200: RegistrationList;
};

export type ListByCertificationResponse = ListByCertificationResponses[keyof ListByCertificationResponses];

export type ListByFirmwareData = {
    body?: never;
    path: {
        depot: string;
        channel: GearFirmwareChannel;
    };
    query?: {
        /**
         * Opaque cursor returned by the previous list response
         */
        cursor?: string;
        /**
         * Maximum number of items to return. Omitted or non-positive values use the default page size; values above 200 are clamped.
         */
        limit?: number;
    };
    url: '/gears/firmware/{depot}/{channel}';
};

export type ListByFirmwareErrors = {
    /**
     * Internal error
     */
    500: ErrorResponse;
};

export type ListByFirmwareError = ListByFirmwareErrors[keyof ListByFirmwareErrors];

export type ListByFirmwareResponses = {
    /**
     * Matched gears
     */
    200: RegistrationList;
};

export type ListByFirmwareResponse = ListByFirmwareResponses[keyof ListByFirmwareResponses];

export type DeleteGearData = {
    body?: never;
    path: {
        /**
         * Gear public key
         */
        publicKey: string;
    };
    query?: never;
    url: '/gears/{publicKey}';
};

export type DeleteGearErrors = {
    /**
     * Gear not found
     */
    404: ErrorResponse;
};

export type DeleteGearError = DeleteGearErrors[keyof DeleteGearErrors];

export type DeleteGearResponses = {
    /**
     * Deleted gear registration
     */
    200: Registration;
};

export type DeleteGearResponse = DeleteGearResponses[keyof DeleteGearResponses];

export type GetGearData = {
    body?: never;
    path: {
        /**
         * Gear public key
         */
        publicKey: string;
    };
    query?: never;
    url: '/gears/{publicKey}';
};

export type GetGearErrors = {
    /**
     * Gear not found
     */
    404: ErrorResponse;
};

export type GetGearError = GetGearErrors[keyof GetGearErrors];

export type GetGearResponses = {
    /**
     * Gear registration
     */
    200: Registration;
};

export type GetGearResponse = GetGearResponses[keyof GetGearResponses];

export type ApproveGearData = {
    body: ApproveRequest;
    path: {
        /**
         * Gear public key
         */
        publicKey: string;
    };
    query?: never;
    url: '/gears/{publicKey}/@approve';
};

export type ApproveGearErrors = {
    /**
     * Invalid role
     */
    400: ErrorResponse;
};

export type ApproveGearError = ApproveGearErrors[keyof ApproveGearErrors];

export type ApproveGearResponses = {
    /**
     * Approved gear registration
     */
    200: Registration;
};

export type ApproveGearResponse = ApproveGearResponses[keyof ApproveGearResponses];

export type BlockGearData = {
    body?: never;
    path: {
        /**
         * Gear public key
         */
        publicKey: string;
    };
    query?: never;
    url: '/gears/{publicKey}/@block';
};

export type BlockGearErrors = {
    /**
     * Gear not found
     */
    404: ErrorResponse;
};

export type BlockGearError = BlockGearErrors[keyof BlockGearErrors];

export type BlockGearResponses = {
    /**
     * Blocked gear registration
     */
    200: Registration;
};

export type BlockGearResponse = BlockGearResponses[keyof BlockGearResponses];

export type RefreshGearData = {
    body?: never;
    path: {
        /**
         * Gear public key
         */
        publicKey: string;
    };
    query?: never;
    url: '/gears/{publicKey}/@refresh';
};

export type RefreshGearErrors = {
    /**
     * Gear not found
     */
    404: ErrorResponse;
    /**
     * Device offline
     */
    409: ErrorResponse;
    /**
     * Device refresh failed
     */
    502: ErrorResponse;
};

export type RefreshGearError = RefreshGearErrors[keyof RefreshGearErrors];

export type RefreshGearResponses = {
    /**
     * Refresh result
     */
    200: RefreshResult;
};

export type RefreshGearResponse = RefreshGearResponses[keyof RefreshGearResponses];

export type GetGearInfoData = {
    body?: never;
    path: {
        /**
         * Gear public key
         */
        publicKey: string;
    };
    query?: never;
    url: '/gears/{publicKey}/info';
};

export type GetGearInfoErrors = {
    /**
     * Gear not found
     */
    404: ErrorResponse;
};

export type GetGearInfoError = GetGearInfoErrors[keyof GetGearInfoErrors];

export type GetGearInfoResponses = {
    /**
     * Device info
     */
    200: DeviceInfo;
};

export type GetGearInfoResponse = GetGearInfoResponses[keyof GetGearInfoResponses];

export type GetGearConfigData = {
    body?: never;
    path: {
        /**
         * Gear public key
         */
        publicKey: string;
    };
    query?: never;
    url: '/gears/{publicKey}/config';
};

export type GetGearConfigErrors = {
    /**
     * Gear not found
     */
    404: ErrorResponse;
};

export type GetGearConfigError = GetGearConfigErrors[keyof GetGearConfigErrors];

export type GetGearConfigResponses = {
    /**
     * Configuration
     */
    200: Configuration;
};

export type GetGearConfigResponse = GetGearConfigResponses[keyof GetGearConfigResponses];

export type PutGearConfigData = {
    body: Configuration;
    path: {
        /**
         * Gear public key
         */
        publicKey: string;
    };
    query?: never;
    url: '/gears/{publicKey}/config';
};

export type PutGearConfigErrors = {
    /**
     * Invalid params
     */
    400: ErrorResponse;
    /**
     * Gear not found
     */
    404: ErrorResponse;
};

export type PutGearConfigError = PutGearConfigErrors[keyof PutGearConfigErrors];

export type PutGearConfigResponses = {
    /**
     * Updated configuration
     */
    200: Configuration;
};

export type PutGearConfigResponse = PutGearConfigResponses[keyof PutGearConfigResponses];

export type GetGearRuntimeData = {
    body?: never;
    path: {
        /**
         * Gear public key
         */
        publicKey: string;
    };
    query?: never;
    url: '/gears/{publicKey}/runtime';
};

export type GetGearRuntimeResponses = {
    /**
     * Runtime status
     */
    200: Runtime;
};

export type GetGearRuntimeResponse = GetGearRuntimeResponses[keyof GetGearRuntimeResponses];

export type GetGearOtaData = {
    body?: never;
    path: {
        /**
         * Gear public key
         */
        publicKey: string;
    };
    query?: never;
    url: '/gears/{publicKey}/ota';
};

export type GetGearOtaErrors = {
    /**
     * Gear or firmware not found
     */
    404: ErrorResponse;
};

export type GetGearOtaError = GetGearOtaErrors[keyof GetGearOtaErrors];

export type GetGearOtaResponses = {
    /**
     * OTA summary
     */
    200: OtaSummary;
};

export type GetGearOtaResponse = GetGearOtaResponses[keyof GetGearOtaResponses];
