// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package apitypes

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ApplyAction.
const (
	ApplyActionApplied   ApplyAction = "applied"
	ApplyActionCreated   ApplyAction = "created"
	ApplyActionUnchanged ApplyAction = "unchanged"
	ApplyActionUpdated   ApplyAction = "updated"
)

// Valid indicates whether the value is a known member of the ApplyAction enum.
func (e ApplyAction) Valid() bool {
	switch e {
	case ApplyActionApplied:
		return true
	case ApplyActionCreated:
		return true
	case ApplyActionUnchanged:
		return true
	case ApplyActionUpdated:
		return true
	default:
		return false
	}
}

// Defines values for CredentialMethod.
const (
	CredentialMethodApiKey     CredentialMethod = "api_key"
	CredentialMethodAppIdToken CredentialMethod = "app_id_token"
	CredentialMethodToken      CredentialMethod = "token"
)

// Valid indicates whether the value is a known member of the CredentialMethod enum.
func (e CredentialMethod) Valid() bool {
	switch e {
	case CredentialMethodApiKey:
		return true
	case CredentialMethodAppIdToken:
		return true
	case CredentialMethodToken:
		return true
	default:
		return false
	}
}

// Defines values for CredentialResourceKind.
const (
	CredentialResourceKindCredential CredentialResourceKind = "Credential"
)

// Valid indicates whether the value is a known member of the CredentialResourceKind enum.
func (e CredentialResourceKind) Valid() bool {
	switch e {
	case CredentialResourceKindCredential:
		return true
	default:
		return false
	}
}

// Defines values for GearCertificationAuthority.
const (
	GearCertificationAuthorityCcc      GearCertificationAuthority = "ccc"
	GearCertificationAuthorityCe       GearCertificationAuthority = "ce"
	GearCertificationAuthorityFcc      GearCertificationAuthority = "fcc"
	GearCertificationAuthorityInternal GearCertificationAuthority = "internal"
	GearCertificationAuthorityMiit     GearCertificationAuthority = "miit"
	GearCertificationAuthorityRohs     GearCertificationAuthority = "rohs"
	GearCertificationAuthoritySrrc     GearCertificationAuthority = "srrc"
	GearCertificationAuthorityUnknown  GearCertificationAuthority = "unknown"
)

// Valid indicates whether the value is a known member of the GearCertificationAuthority enum.
func (e GearCertificationAuthority) Valid() bool {
	switch e {
	case GearCertificationAuthorityCcc:
		return true
	case GearCertificationAuthorityCe:
		return true
	case GearCertificationAuthorityFcc:
		return true
	case GearCertificationAuthorityInternal:
		return true
	case GearCertificationAuthorityMiit:
		return true
	case GearCertificationAuthorityRohs:
		return true
	case GearCertificationAuthoritySrrc:
		return true
	case GearCertificationAuthorityUnknown:
		return true
	default:
		return false
	}
}

// Defines values for GearCertificationType.
const (
	GearCertificationTypeCertification GearCertificationType = "certification"
	GearCertificationTypeLicense       GearCertificationType = "license"
)

// Valid indicates whether the value is a known member of the GearCertificationType enum.
func (e GearCertificationType) Valid() bool {
	switch e {
	case GearCertificationTypeCertification:
		return true
	case GearCertificationTypeLicense:
		return true
	default:
		return false
	}
}

// Defines values for GearConfigResourceKind.
const (
	GearConfigResourceKindGearConfig GearConfigResourceKind = "GearConfig"
)

// Valid indicates whether the value is a known member of the GearConfigResourceKind enum.
func (e GearConfigResourceKind) Valid() bool {
	switch e {
	case GearConfigResourceKindGearConfig:
		return true
	default:
		return false
	}
}

// Defines values for GearRole.
const (
	GearRoleAdmin       GearRole = "admin"
	GearRoleGear        GearRole = "gear"
	GearRoleServer      GearRole = "server"
	GearRoleUnspecified GearRole = "unspecified"
)

// Valid indicates whether the value is a known member of the GearRole enum.
func (e GearRole) Valid() bool {
	switch e {
	case GearRoleAdmin:
		return true
	case GearRoleGear:
		return true
	case GearRoleServer:
		return true
	case GearRoleUnspecified:
		return true
	default:
		return false
	}
}

// Defines values for GearStatus.
const (
	GearStatusActive      GearStatus = "active"
	GearStatusBlocked     GearStatus = "blocked"
	GearStatusUnspecified GearStatus = "unspecified"
)

// Valid indicates whether the value is a known member of the GearStatus enum.
func (e GearStatus) Valid() bool {
	switch e {
	case GearStatusActive:
		return true
	case GearStatusBlocked:
		return true
	case GearStatusUnspecified:
		return true
	default:
		return false
	}
}

// Defines values for MiniMaxTenantResourceKind.
const (
	MiniMaxTenantResourceKindMiniMaxTenant MiniMaxTenantResourceKind = "MiniMaxTenant"
)

// Valid indicates whether the value is a known member of the MiniMaxTenantResourceKind enum.
func (e MiniMaxTenantResourceKind) Valid() bool {
	switch e {
	case MiniMaxTenantResourceKindMiniMaxTenant:
		return true
	default:
		return false
	}
}

// Defines values for MultiAgentGraphWorkflowTemplateKind.
const (
	MultiAgentGraphWorkflowTemplateKindMultiAgentGraphWorkflowTemplate MultiAgentGraphWorkflowTemplateKind = "MultiAgentGraphWorkflowTemplate"
)

// Valid indicates whether the value is a known member of the MultiAgentGraphWorkflowTemplateKind enum.
func (e MultiAgentGraphWorkflowTemplateKind) Valid() bool {
	switch e {
	case MultiAgentGraphWorkflowTemplateKindMultiAgentGraphWorkflowTemplate:
		return true
	default:
		return false
	}
}

// Defines values for ResourceAPIVersion.
const (
	ResourceAPIVersionGizclawAdminv1alpha1 ResourceAPIVersion = "gizclaw.admin/v1alpha1"
)

// Valid indicates whether the value is a known member of the ResourceAPIVersion enum.
func (e ResourceAPIVersion) Valid() bool {
	switch e {
	case ResourceAPIVersionGizclawAdminv1alpha1:
		return true
	default:
		return false
	}
}

// Defines values for ResourceKind.
const (
	ResourceKindCredential        ResourceKind = "Credential"
	ResourceKindGearConfig        ResourceKind = "GearConfig"
	ResourceKindMiniMaxTenant     ResourceKind = "MiniMaxTenant"
	ResourceKindResourceList      ResourceKind = "ResourceList"
	ResourceKindVoice             ResourceKind = "Voice"
	ResourceKindWorkspace         ResourceKind = "Workspace"
	ResourceKindWorkspaceTemplate ResourceKind = "WorkspaceTemplate"
)

// Valid indicates whether the value is a known member of the ResourceKind enum.
func (e ResourceKind) Valid() bool {
	switch e {
	case ResourceKindCredential:
		return true
	case ResourceKindGearConfig:
		return true
	case ResourceKindMiniMaxTenant:
		return true
	case ResourceKindResourceList:
		return true
	case ResourceKindVoice:
		return true
	case ResourceKindWorkspace:
		return true
	case ResourceKindWorkspaceTemplate:
		return true
	default:
		return false
	}
}

// Defines values for ResourceListResourceKind.
const (
	ResourceListResourceKindResourceList ResourceListResourceKind = "ResourceList"
)

// Valid indicates whether the value is a known member of the ResourceListResourceKind enum.
func (e ResourceListResourceKind) Valid() bool {
	switch e {
	case ResourceListResourceKindResourceList:
		return true
	default:
		return false
	}
}

// Defines values for SingleAgentGraphWorkflowTemplateKind.
const (
	SingleAgentGraphWorkflowTemplateKindSingleAgentGraphWorkflowTemplate SingleAgentGraphWorkflowTemplateKind = "SingleAgentGraphWorkflowTemplate"
)

// Valid indicates whether the value is a known member of the SingleAgentGraphWorkflowTemplateKind enum.
func (e SingleAgentGraphWorkflowTemplateKind) Valid() bool {
	switch e {
	case SingleAgentGraphWorkflowTemplateKindSingleAgentGraphWorkflowTemplate:
		return true
	default:
		return false
	}
}

// Defines values for VoiceResourceKind.
const (
	VoiceResourceKindVoice VoiceResourceKind = "Voice"
)

// Valid indicates whether the value is a known member of the VoiceResourceKind enum.
func (e VoiceResourceKind) Valid() bool {
	switch e {
	case VoiceResourceKindVoice:
		return true
	default:
		return false
	}
}

// Defines values for VoiceSource.
const (
	VoiceSourceManual VoiceSource = "manual"
	VoiceSourceSync   VoiceSource = "sync"
)

// Valid indicates whether the value is a known member of the VoiceSource enum.
func (e VoiceSource) Valid() bool {
	switch e {
	case VoiceSourceManual:
		return true
	case VoiceSourceSync:
		return true
	default:
		return false
	}
}

// Defines values for WorkflowTemplateAPIVersion.
const (
	WorkflowTemplateAPIVersionGizclawFlowcraftv1alpha1 WorkflowTemplateAPIVersion = "gizclaw.flowcraft/v1alpha1"
)

// Valid indicates whether the value is a known member of the WorkflowTemplateAPIVersion enum.
func (e WorkflowTemplateAPIVersion) Valid() bool {
	switch e {
	case WorkflowTemplateAPIVersionGizclawFlowcraftv1alpha1:
		return true
	default:
		return false
	}
}

// Defines values for WorkspaceResourceKind.
const (
	WorkspaceResourceKindWorkspace WorkspaceResourceKind = "Workspace"
)

// Valid indicates whether the value is a known member of the WorkspaceResourceKind enum.
func (e WorkspaceResourceKind) Valid() bool {
	switch e {
	case WorkspaceResourceKindWorkspace:
		return true
	default:
		return false
	}
}

// Defines values for WorkspaceTemplateResourceKind.
const (
	WorkspaceTemplateResourceKindWorkspaceTemplate WorkspaceTemplateResourceKind = "WorkspaceTemplate"
)

// Valid indicates whether the value is a known member of the WorkspaceTemplateResourceKind enum.
func (e WorkspaceTemplateResourceKind) Valid() bool {
	switch e {
	case WorkspaceTemplateResourceKindWorkspaceTemplate:
		return true
	default:
		return false
	}
}

// ApplyAction Result of applying the resource.
type ApplyAction string

// ApplyResource defines model for ApplyResource.
type ApplyResource = Resource

// ApplyResult defines model for ApplyResult.
type ApplyResult struct {
	// Action Result of applying the resource.
	Action ApplyAction `json:"action"`

	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion `json:"apiVersion"`

	// Items Nested apply results for ResourceList resources.
	Items *[]ApplyResult `json:"items,omitempty"`

	// Kind Declarative GizClaw resource kind.
	Kind    ResourceKind `json:"kind"`
	Message *string      `json:"message,omitempty"`
	Name    string       `json:"name"`
}

// Channel defines model for Channel.
type Channel = string

// Configuration defines model for Configuration.
type Configuration struct {
	Certifications *[]GearCertification `json:"certifications,omitempty"`
	Firmware       *FirmwareConfig      `json:"firmware,omitempty"`
}

// Credential defines model for Credential.
type Credential struct {
	Body        CredentialBody `json:"body"`
	CreatedAt   time.Time      `json:"created_at"`
	Description *string        `json:"description,omitempty"`

	// Method Credential authentication method
	Method CredentialMethod `json:"method"`

	// Name Credential name
	Name CredentialName `json:"name"`

	// Provider Credential provider name
	Provider  CredentialProvider `json:"provider"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// CredentialBody defines model for CredentialBody.
type CredentialBody map[string]interface{}

// CredentialMethod Credential authentication method
type CredentialMethod string

// CredentialName Credential name
type CredentialName = string

// CredentialProvider Credential provider name
type CredentialProvider = string

// CredentialResource defines model for CredentialResource.
type CredentialResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion     `json:"apiVersion"`
	Kind       CredentialResourceKind `json:"kind"`
	Metadata   ResourceMetadata       `json:"metadata"`
	Spec       CredentialSpec         `json:"spec"`
}

// CredentialResourceKind defines model for CredentialResource.Kind.
type CredentialResourceKind string

// CredentialSpec defines model for CredentialSpec.
type CredentialSpec struct {
	Body        CredentialBody `json:"body"`
	Description *string        `json:"description,omitempty"`

	// Method Credential authentication method
	Method CredentialMethod `json:"method"`

	// Provider Credential provider name
	Provider CredentialProvider `json:"provider"`
}

// Depot defines model for Depot.
type Depot struct {
	Beta     DepotRelease `json:"beta"`
	Info     DepotInfo    `json:"info"`
	Name     string       `json:"name"`
	Rollback DepotRelease `json:"rollback"`
	Stable   DepotRelease `json:"stable"`
	Testing  DepotRelease `json:"testing"`
}

// DepotFile defines model for DepotFile.
type DepotFile struct {
	Md5    string `json:"md5"`
	Path   string `json:"path"`
	Sha256 string `json:"sha256"`
}

// DepotInfo defines model for DepotInfo.
type DepotInfo struct {
	Files *[]DepotInfoFile `json:"files,omitempty"`
}

// DepotInfoFile defines model for DepotInfoFile.
type DepotInfoFile struct {
	Path string `json:"path"`
}

// DepotRelease defines model for DepotRelease.
type DepotRelease struct {
	Channel        *string      `json:"channel,omitempty"`
	Files          *[]DepotFile `json:"files,omitempty"`
	FirmwareSemver string       `json:"firmware_semver"`
}

// DeviceInfo defines model for DeviceInfo.
type DeviceInfo struct {
	Hardware *HardwareInfo `json:"hardware,omitempty"`
	Name     *string       `json:"name,omitempty"`
	Sn       *string       `json:"sn,omitempty"`
}

// ErrorPayload defines model for ErrorPayload.
type ErrorPayload struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorPayload `json:"error"`
}

// FirmwareConfig defines model for FirmwareConfig.
type FirmwareConfig struct {
	Channel *GearFirmwareChannel `json:"channel,omitempty"`
}

// Gear defines model for Gear.
type Gear struct {
	ApprovedAt     *time.Time    `json:"approved_at,omitempty"`
	AutoRegistered *bool         `json:"auto_registered,omitempty"`
	Configuration  Configuration `json:"configuration"`
	CreatedAt      time.Time     `json:"created_at"`
	Device         DeviceInfo    `json:"device"`
	PublicKey      string        `json:"public_key"`
	Role           GearRole      `json:"role"`
	Status         GearStatus    `json:"status"`
	UpdatedAt      time.Time     `json:"updated_at"`
}

// GearCertification defines model for GearCertification.
type GearCertification struct {
	Authority     GearCertificationAuthority `json:"authority"`
	AuthorityName *string                    `json:"authority_name,omitempty"`
	Id            string                     `json:"id"`
	Type          GearCertificationType      `json:"type"`
}

// GearCertificationAuthority defines model for GearCertificationAuthority.
type GearCertificationAuthority string

// GearCertificationType defines model for GearCertificationType.
type GearCertificationType string

// GearConfigResource defines model for GearConfigResource.
type GearConfigResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion     `json:"apiVersion"`
	Kind       GearConfigResourceKind `json:"kind"`
	Metadata   ResourceMetadata       `json:"metadata"`
	Spec       Configuration          `json:"spec"`
}

// GearConfigResourceKind defines model for GearConfigResource.Kind.
type GearConfigResourceKind string

// GearFirmwareChannel defines model for GearFirmwareChannel.
type GearFirmwareChannel = string

// GearIMEI defines model for GearIMEI.
type GearIMEI struct {
	Name   *string `json:"name,omitempty"`
	Serial string  `json:"serial"`
	Tac    string  `json:"tac"`
}

// GearLabel defines model for GearLabel.
type GearLabel struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// GearRole defines model for GearRole.
type GearRole string

// GearStatus defines model for GearStatus.
type GearStatus string

// HardwareInfo defines model for HardwareInfo.
type HardwareInfo struct {
	Depot            *string      `json:"depot,omitempty"`
	FirmwareSemver   *string      `json:"firmware_semver,omitempty"`
	HardwareRevision *string      `json:"hardware_revision,omitempty"`
	Imeis            *[]GearIMEI  `json:"imeis,omitempty"`
	Labels           *[]GearLabel `json:"labels,omitempty"`
	Manufacturer     *string      `json:"manufacturer,omitempty"`
	Model            *string      `json:"model,omitempty"`
}

// MiniMaxAppID MiniMax app identifier
type MiniMaxAppID = string

// MiniMaxGroupID MiniMax group identifier
type MiniMaxGroupID = string

// MiniMaxTenant defines model for MiniMaxTenant.
type MiniMaxTenant struct {
	// AppId MiniMax app identifier
	AppId     MiniMaxAppID `json:"app_id"`
	BaseUrl   *string      `json:"base_url,omitempty"`
	CreatedAt time.Time    `json:"created_at"`

	// CredentialName Credential name
	CredentialName CredentialName `json:"credential_name"`
	Description    *string        `json:"description,omitempty"`

	// GroupId MiniMax group identifier
	GroupId      MiniMaxGroupID `json:"group_id"`
	LastSyncedAt *time.Time     `json:"last_synced_at,omitempty"`

	// Name MiniMax tenant name
	Name      MiniMaxTenantName `json:"name"`
	UpdatedAt time.Time         `json:"updated_at"`
}

// MiniMaxTenantName MiniMax tenant name
type MiniMaxTenantName = string

// MiniMaxTenantResource defines model for MiniMaxTenantResource.
type MiniMaxTenantResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion        `json:"apiVersion"`
	Kind       MiniMaxTenantResourceKind `json:"kind"`
	Metadata   ResourceMetadata          `json:"metadata"`
	Spec       MiniMaxTenantSpec         `json:"spec"`
}

// MiniMaxTenantResourceKind defines model for MiniMaxTenantResource.Kind.
type MiniMaxTenantResourceKind string

// MiniMaxTenantSpec defines model for MiniMaxTenantSpec.
type MiniMaxTenantSpec struct {
	// AppId MiniMax app identifier
	AppId   MiniMaxAppID `json:"app_id"`
	BaseUrl *string      `json:"base_url,omitempty"`

	// CredentialName Credential name
	CredentialName CredentialName `json:"credential_name"`
	Description    *string        `json:"description,omitempty"`

	// GroupId MiniMax group identifier
	GroupId MiniMaxGroupID `json:"group_id"`
}

// MultiAgentGraphWorkflowSpec defines model for MultiAgentGraphWorkflowSpec.
type MultiAgentGraphWorkflowSpec = map[string]interface{}

// MultiAgentGraphWorkflowTemplate defines model for MultiAgentGraphWorkflowTemplate.
type MultiAgentGraphWorkflowTemplate struct {
	ApiVersion WorkflowTemplateAPIVersion          `json:"apiVersion"`
	Kind       MultiAgentGraphWorkflowTemplateKind `json:"kind"`
	Metadata   TemplateMetadata                    `json:"metadata"`
	Spec       MultiAgentGraphWorkflowSpec         `json:"spec"`
}

// MultiAgentGraphWorkflowTemplateKind defines model for MultiAgentGraphWorkflowTemplate.Kind.
type MultiAgentGraphWorkflowTemplateKind string

// OTASummary defines model for OTASummary.
type OTASummary struct {
	Channel        string      `json:"channel"`
	Depot          string      `json:"depot"`
	Files          []DepotFile `json:"files"`
	FirmwareSemver string      `json:"firmware_semver"`
}

// RefreshIdentifiers defines model for RefreshIdentifiers.
type RefreshIdentifiers struct {
	Imeis  *[]GearIMEI  `json:"imeis,omitempty"`
	Labels *[]GearLabel `json:"labels,omitempty"`
	Sn     *string      `json:"sn,omitempty"`
}

// RefreshInfo defines model for RefreshInfo.
type RefreshInfo struct {
	HardwareRevision *string `json:"hardware_revision,omitempty"`
	Manufacturer     *string `json:"manufacturer,omitempty"`
	Model            *string `json:"model,omitempty"`
	Name             *string `json:"name,omitempty"`
}

// RefreshVersion defines model for RefreshVersion.
type RefreshVersion struct {
	Depot          *string `json:"depot,omitempty"`
	FirmwareSemver *string `json:"firmware_semver,omitempty"`
}

// Registration defines model for Registration.
type Registration struct {
	ApprovedAt     *time.Time `json:"approved_at,omitempty"`
	AutoRegistered *bool      `json:"auto_registered,omitempty"`
	CreatedAt      time.Time  `json:"created_at"`
	PublicKey      string     `json:"public_key"`
	Role           GearRole   `json:"role"`
	Status         GearStatus `json:"status"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

// Resource defines model for Resource.
type Resource struct {
	union json.RawMessage
}

// ResourceAPIVersion API version for declarative GizClaw resources.
type ResourceAPIVersion string

// ResourceKind Declarative GizClaw resource kind.
type ResourceKind string

// ResourceList defines model for ResourceList.
type ResourceList = ResourceListResource

// ResourceListResource defines model for ResourceListResource.
type ResourceListResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion       `json:"apiVersion"`
	Kind       ResourceListResourceKind `json:"kind"`
	Metadata   ResourceMetadata         `json:"metadata"`
	Spec       ResourceListSpec         `json:"spec"`
}

// ResourceListResourceKind defines model for ResourceListResource.Kind.
type ResourceListResourceKind string

// ResourceListSpec defines model for ResourceListSpec.
type ResourceListSpec struct {
	Items []Resource `json:"items"`
}

// ResourceMetadata defines model for ResourceMetadata.
type ResourceMetadata struct {
	Annotations *map[string]string `json:"annotations,omitempty"`
	Labels      *map[string]string `json:"labels,omitempty"`

	// Name Resource name. For GearConfig this is the gear public key.
	Name string `json:"name"`
}

// Runtime defines model for Runtime.
type Runtime struct {
	LastAddr   *string   `json:"last_addr,omitempty"`
	LastSeenAt time.Time `json:"last_seen_at"`
	Online     bool      `json:"online"`
}

// ServerInfo defines model for ServerInfo.
type ServerInfo struct {
	BuildCommit string `json:"build_commit"`
	PublicKey   string `json:"public_key"`
	ServerTime  int64  `json:"server_time"`
}

// SingleAgentGraphWorkflowSpec defines model for SingleAgentGraphWorkflowSpec.
type SingleAgentGraphWorkflowSpec = map[string]interface{}

// SingleAgentGraphWorkflowTemplate defines model for SingleAgentGraphWorkflowTemplate.
type SingleAgentGraphWorkflowTemplate struct {
	ApiVersion WorkflowTemplateAPIVersion           `json:"apiVersion"`
	Kind       SingleAgentGraphWorkflowTemplateKind `json:"kind"`
	Metadata   TemplateMetadata                     `json:"metadata"`
	Spec       SingleAgentGraphWorkflowSpec         `json:"spec"`
}

// SingleAgentGraphWorkflowTemplateKind defines model for SingleAgentGraphWorkflowTemplate.Kind.
type SingleAgentGraphWorkflowTemplateKind string

// TemplateMetadata defines model for TemplateMetadata.
type TemplateMetadata struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// Voice defines model for Voice.
type Voice struct {
	CreatedAt   time.Time `json:"created_at"`
	Description *string   `json:"description,omitempty"`

	// Id Global voice identifier
	Id       VoiceID       `json:"id"`
	Name     *string       `json:"name,omitempty"`
	Provider VoiceProvider `json:"provider"`

	// ProviderVoiceId Upstream provider voice identifier. Present for synced voices.
	ProviderVoiceId *string `json:"provider_voice_id,omitempty"`

	// ProviderVoiceType Provider-specific voice type
	ProviderVoiceType *string                 `json:"provider_voice_type,omitempty"`
	Raw               *map[string]interface{} `json:"raw,omitempty"`

	// Source How the voice entered the global catalog
	Source    VoiceSource `json:"source"`
	SyncedAt  *time.Time  `json:"synced_at,omitempty"`
	UpdatedAt time.Time   `json:"updated_at"`
}

// VoiceID Global voice identifier
type VoiceID = string

// VoiceProvider defines model for VoiceProvider.
type VoiceProvider struct {
	// Kind Voice provider kind
	Kind VoiceProviderKind `json:"kind"`

	// Name Voice provider instance name
	Name VoiceProviderName `json:"name"`
}

// VoiceProviderKind Voice provider kind
type VoiceProviderKind = string

// VoiceProviderName Voice provider instance name
type VoiceProviderName = string

// VoiceResource defines model for VoiceResource.
type VoiceResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion `json:"apiVersion"`
	Kind       VoiceResourceKind  `json:"kind"`
	Metadata   ResourceMetadata   `json:"metadata"`
	Spec       VoiceSpec          `json:"spec"`
}

// VoiceResourceKind defines model for VoiceResource.Kind.
type VoiceResourceKind string

// VoiceSource How the voice entered the global catalog
type VoiceSource string

// VoiceSpec defines model for VoiceSpec.
type VoiceSpec struct {
	Description *string       `json:"description,omitempty"`
	Name        *string       `json:"name,omitempty"`
	Provider    VoiceProvider `json:"provider"`

	// ProviderVoiceId Upstream provider voice identifier. Present for synced voices.
	ProviderVoiceId *string `json:"provider_voice_id,omitempty"`

	// ProviderVoiceType Provider-specific voice type
	ProviderVoiceType *string                 `json:"provider_voice_type,omitempty"`
	Raw               *map[string]interface{} `json:"raw,omitempty"`

	// Source How the voice entered the global catalog
	Source VoiceSource `json:"source"`
}

// WorkflowTemplateAPIVersion defines model for WorkflowTemplateAPIVersion.
type WorkflowTemplateAPIVersion string

// WorkflowTemplateDocument defines model for WorkflowTemplateDocument.
type WorkflowTemplateDocument struct {
	union json.RawMessage
}

// Workspace defines model for Workspace.
type Workspace struct {
	CreatedAt time.Time `json:"created_at"`

	// Name Workspace name
	Name       WorkspaceName           `json:"name"`
	Parameters *map[string]interface{} `json:"parameters,omitempty"`
	UpdatedAt  time.Time               `json:"updated_at"`

	// WorkspaceTemplateName Workspace template name
	WorkspaceTemplateName WorkspaceTemplateName `json:"workspace_template_name"`
}

// WorkspaceName Workspace name
type WorkspaceName = string

// WorkspaceResource defines model for WorkspaceResource.
type WorkspaceResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion    `json:"apiVersion"`
	Kind       WorkspaceResourceKind `json:"kind"`
	Metadata   ResourceMetadata      `json:"metadata"`
	Spec       WorkspaceSpec         `json:"spec"`
}

// WorkspaceResourceKind defines model for WorkspaceResource.Kind.
type WorkspaceResourceKind string

// WorkspaceSpec defines model for WorkspaceSpec.
type WorkspaceSpec struct {
	Parameters *map[string]interface{} `json:"parameters,omitempty"`

	// WorkspaceTemplateName Workspace template name
	WorkspaceTemplateName WorkspaceTemplateName `json:"workspace_template_name"`
}

// WorkspaceTemplateName Workspace template name
type WorkspaceTemplateName = string

// WorkspaceTemplateResource defines model for WorkspaceTemplateResource.
type WorkspaceTemplateResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion            `json:"apiVersion"`
	Kind       WorkspaceTemplateResourceKind `json:"kind"`
	Metadata   ResourceMetadata              `json:"metadata"`
	Spec       WorkflowTemplateDocument      `json:"spec"`
}

// WorkspaceTemplateResourceKind defines model for WorkspaceTemplateResource.Kind.
type WorkspaceTemplateResourceKind string

// AsCredentialResource returns the union data inside the Resource as a CredentialResource
func (t Resource) AsCredentialResource() (CredentialResource, error) {
	var body CredentialResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCredentialResource overwrites any union data inside the Resource as the provided CredentialResource
func (t *Resource) FromCredentialResource(v CredentialResource) error {
	v.Kind = "CredentialResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCredentialResource performs a merge with any union data inside the Resource, using the provided CredentialResource
func (t *Resource) MergeCredentialResource(v CredentialResource) error {
	v.Kind = "CredentialResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMiniMaxTenantResource returns the union data inside the Resource as a MiniMaxTenantResource
func (t Resource) AsMiniMaxTenantResource() (MiniMaxTenantResource, error) {
	var body MiniMaxTenantResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMiniMaxTenantResource overwrites any union data inside the Resource as the provided MiniMaxTenantResource
func (t *Resource) FromMiniMaxTenantResource(v MiniMaxTenantResource) error {
	v.Kind = "MiniMaxTenantResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMiniMaxTenantResource performs a merge with any union data inside the Resource, using the provided MiniMaxTenantResource
func (t *Resource) MergeMiniMaxTenantResource(v MiniMaxTenantResource) error {
	v.Kind = "MiniMaxTenantResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsVoiceResource returns the union data inside the Resource as a VoiceResource
func (t Resource) AsVoiceResource() (VoiceResource, error) {
	var body VoiceResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVoiceResource overwrites any union data inside the Resource as the provided VoiceResource
func (t *Resource) FromVoiceResource(v VoiceResource) error {
	v.Kind = "VoiceResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVoiceResource performs a merge with any union data inside the Resource, using the provided VoiceResource
func (t *Resource) MergeVoiceResource(v VoiceResource) error {
	v.Kind = "VoiceResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWorkspaceTemplateResource returns the union data inside the Resource as a WorkspaceTemplateResource
func (t Resource) AsWorkspaceTemplateResource() (WorkspaceTemplateResource, error) {
	var body WorkspaceTemplateResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWorkspaceTemplateResource overwrites any union data inside the Resource as the provided WorkspaceTemplateResource
func (t *Resource) FromWorkspaceTemplateResource(v WorkspaceTemplateResource) error {
	v.Kind = "WorkspaceTemplateResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWorkspaceTemplateResource performs a merge with any union data inside the Resource, using the provided WorkspaceTemplateResource
func (t *Resource) MergeWorkspaceTemplateResource(v WorkspaceTemplateResource) error {
	v.Kind = "WorkspaceTemplateResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWorkspaceResource returns the union data inside the Resource as a WorkspaceResource
func (t Resource) AsWorkspaceResource() (WorkspaceResource, error) {
	var body WorkspaceResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWorkspaceResource overwrites any union data inside the Resource as the provided WorkspaceResource
func (t *Resource) FromWorkspaceResource(v WorkspaceResource) error {
	v.Kind = "WorkspaceResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWorkspaceResource performs a merge with any union data inside the Resource, using the provided WorkspaceResource
func (t *Resource) MergeWorkspaceResource(v WorkspaceResource) error {
	v.Kind = "WorkspaceResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGearConfigResource returns the union data inside the Resource as a GearConfigResource
func (t Resource) AsGearConfigResource() (GearConfigResource, error) {
	var body GearConfigResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGearConfigResource overwrites any union data inside the Resource as the provided GearConfigResource
func (t *Resource) FromGearConfigResource(v GearConfigResource) error {
	v.Kind = "GearConfigResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGearConfigResource performs a merge with any union data inside the Resource, using the provided GearConfigResource
func (t *Resource) MergeGearConfigResource(v GearConfigResource) error {
	v.Kind = "GearConfigResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsResourceListResource returns the union data inside the Resource as a ResourceListResource
func (t Resource) AsResourceListResource() (ResourceListResource, error) {
	var body ResourceListResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResourceListResource overwrites any union data inside the Resource as the provided ResourceListResource
func (t *Resource) FromResourceListResource(v ResourceListResource) error {
	v.Kind = "ResourceListResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResourceListResource performs a merge with any union data inside the Resource, using the provided ResourceListResource
func (t *Resource) MergeResourceListResource(v ResourceListResource) error {
	v.Kind = "ResourceListResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Resource) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Resource) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "CredentialResource":
		return t.AsCredentialResource()
	case "GearConfigResource":
		return t.AsGearConfigResource()
	case "MiniMaxTenantResource":
		return t.AsMiniMaxTenantResource()
	case "ResourceListResource":
		return t.AsResourceListResource()
	case "VoiceResource":
		return t.AsVoiceResource()
	case "WorkspaceResource":
		return t.AsWorkspaceResource()
	case "WorkspaceTemplateResource":
		return t.AsWorkspaceTemplateResource()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Resource) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Resource) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSingleAgentGraphWorkflowTemplate returns the union data inside the WorkflowTemplateDocument as a SingleAgentGraphWorkflowTemplate
func (t WorkflowTemplateDocument) AsSingleAgentGraphWorkflowTemplate() (SingleAgentGraphWorkflowTemplate, error) {
	var body SingleAgentGraphWorkflowTemplate
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSingleAgentGraphWorkflowTemplate overwrites any union data inside the WorkflowTemplateDocument as the provided SingleAgentGraphWorkflowTemplate
func (t *WorkflowTemplateDocument) FromSingleAgentGraphWorkflowTemplate(v SingleAgentGraphWorkflowTemplate) error {
	v.Kind = "SingleAgentGraphWorkflowTemplate"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSingleAgentGraphWorkflowTemplate performs a merge with any union data inside the WorkflowTemplateDocument, using the provided SingleAgentGraphWorkflowTemplate
func (t *WorkflowTemplateDocument) MergeSingleAgentGraphWorkflowTemplate(v SingleAgentGraphWorkflowTemplate) error {
	v.Kind = "SingleAgentGraphWorkflowTemplate"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMultiAgentGraphWorkflowTemplate returns the union data inside the WorkflowTemplateDocument as a MultiAgentGraphWorkflowTemplate
func (t WorkflowTemplateDocument) AsMultiAgentGraphWorkflowTemplate() (MultiAgentGraphWorkflowTemplate, error) {
	var body MultiAgentGraphWorkflowTemplate
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMultiAgentGraphWorkflowTemplate overwrites any union data inside the WorkflowTemplateDocument as the provided MultiAgentGraphWorkflowTemplate
func (t *WorkflowTemplateDocument) FromMultiAgentGraphWorkflowTemplate(v MultiAgentGraphWorkflowTemplate) error {
	v.Kind = "MultiAgentGraphWorkflowTemplate"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMultiAgentGraphWorkflowTemplate performs a merge with any union data inside the WorkflowTemplateDocument, using the provided MultiAgentGraphWorkflowTemplate
func (t *WorkflowTemplateDocument) MergeMultiAgentGraphWorkflowTemplate(v MultiAgentGraphWorkflowTemplate) error {
	v.Kind = "MultiAgentGraphWorkflowTemplate"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t WorkflowTemplateDocument) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t WorkflowTemplateDocument) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "MultiAgentGraphWorkflowTemplate":
		return t.AsMultiAgentGraphWorkflowTemplate()
	case "SingleAgentGraphWorkflowTemplate":
		return t.AsSingleAgentGraphWorkflowTemplate()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t WorkflowTemplateDocument) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *WorkflowTemplateDocument) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
