// Package admingen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package admingen

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// PutDepotInfoJSONRequestBody defines body for PutDepotInfo for application/json ContentType.
type PutDepotInfoJSONRequestBody = DepotInfo

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListDepots request
	ListDepots(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDepot request
	GetDepot(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutDepotInfoWithBody request with any body
	PutDepotInfoWithBody(ctx context.Context, depot DepotName, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutDepotInfo(ctx context.Context, depot DepotName, body PutDepotInfoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetChannel request
	GetChannel(ctx context.Context, depot DepotName, channel Channel, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutChannelWithBody request with any body
	PutChannelWithBody(ctx context.Context, depot DepotName, channel Channel, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReleaseDepot request
	ReleaseDepot(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RollbackDepot request
	RollbackDepot(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListDepots(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDepotsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDepot(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDepotRequest(c.Server, depot)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutDepotInfoWithBody(ctx context.Context, depot DepotName, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutDepotInfoRequestWithBody(c.Server, depot, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutDepotInfo(ctx context.Context, depot DepotName, body PutDepotInfoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutDepotInfoRequest(c.Server, depot, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetChannel(ctx context.Context, depot DepotName, channel Channel, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetChannelRequest(c.Server, depot, channel)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutChannelWithBody(ctx context.Context, depot DepotName, channel Channel, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutChannelRequestWithBody(c.Server, depot, channel, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReleaseDepot(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReleaseDepotRequest(c.Server, depot)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RollbackDepot(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRollbackDepotRequest(c.Server, depot)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListDepotsRequest generates requests for ListDepots
func NewListDepotsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/firmwares")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDepotRequest generates requests for GetDepot
func NewGetDepotRequest(server string, depot DepotName) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "depot", depot, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/firmwares/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutDepotInfoRequest calls the generic PutDepotInfo builder with application/json body
func NewPutDepotInfoRequest(server string, depot DepotName, body PutDepotInfoJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutDepotInfoRequestWithBody(server, depot, "application/json", bodyReader)
}

// NewPutDepotInfoRequestWithBody generates requests for PutDepotInfo with any type of body
func NewPutDepotInfoRequestWithBody(server string, depot DepotName, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "depot", depot, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/firmwares/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetChannelRequest generates requests for GetChannel
func NewGetChannelRequest(server string, depot DepotName, channel Channel) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "depot", depot, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "channel", channel, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/firmwares/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutChannelRequestWithBody generates requests for PutChannel with any type of body
func NewPutChannelRequestWithBody(server string, depot DepotName, channel Channel, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "depot", depot, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "channel", channel, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/firmwares/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewReleaseDepotRequest generates requests for ReleaseDepot
func NewReleaseDepotRequest(server string, depot DepotName) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "depot", depot, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/firmwares/%s:release", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRollbackDepotRequest generates requests for RollbackDepot
func NewRollbackDepotRequest(server string, depot DepotName) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "depot", depot, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/firmwares/%s:rollback", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListDepotsWithResponse request
	ListDepotsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDepotsResponse, error)

	// GetDepotWithResponse request
	GetDepotWithResponse(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*GetDepotResponse, error)

	// PutDepotInfoWithBodyWithResponse request with any body
	PutDepotInfoWithBodyWithResponse(ctx context.Context, depot DepotName, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutDepotInfoResponse, error)

	PutDepotInfoWithResponse(ctx context.Context, depot DepotName, body PutDepotInfoJSONRequestBody, reqEditors ...RequestEditorFn) (*PutDepotInfoResponse, error)

	// GetChannelWithResponse request
	GetChannelWithResponse(ctx context.Context, depot DepotName, channel Channel, reqEditors ...RequestEditorFn) (*GetChannelResponse, error)

	// PutChannelWithBodyWithResponse request with any body
	PutChannelWithBodyWithResponse(ctx context.Context, depot DepotName, channel Channel, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutChannelResponse, error)

	// ReleaseDepotWithResponse request
	ReleaseDepotWithResponse(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*ReleaseDepotResponse, error)

	// RollbackDepotWithResponse request
	RollbackDepotWithResponse(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*RollbackDepotResponse, error)
}

type ListDepotsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DepotList
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListDepotsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDepotsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDepotResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Depot
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetDepotResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDepotResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutDepotInfoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Depot
	JSON400      *ErrorResponse
	JSON409      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PutDepotInfoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutDepotInfoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetChannelResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DepotRelease
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetChannelResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetChannelResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutChannelResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DepotRelease
	JSON409      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PutChannelResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutChannelResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ReleaseDepotResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Depot
	JSON404      *ErrorResponse
	JSON409      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ReleaseDepotResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReleaseDepotResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RollbackDepotResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Depot
	JSON404      *ErrorResponse
	JSON409      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r RollbackDepotResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RollbackDepotResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListDepotsWithResponse request returning *ListDepotsResponse
func (c *ClientWithResponses) ListDepotsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDepotsResponse, error) {
	rsp, err := c.ListDepots(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDepotsResponse(rsp)
}

// GetDepotWithResponse request returning *GetDepotResponse
func (c *ClientWithResponses) GetDepotWithResponse(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*GetDepotResponse, error) {
	rsp, err := c.GetDepot(ctx, depot, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDepotResponse(rsp)
}

// PutDepotInfoWithBodyWithResponse request with arbitrary body returning *PutDepotInfoResponse
func (c *ClientWithResponses) PutDepotInfoWithBodyWithResponse(ctx context.Context, depot DepotName, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutDepotInfoResponse, error) {
	rsp, err := c.PutDepotInfoWithBody(ctx, depot, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutDepotInfoResponse(rsp)
}

func (c *ClientWithResponses) PutDepotInfoWithResponse(ctx context.Context, depot DepotName, body PutDepotInfoJSONRequestBody, reqEditors ...RequestEditorFn) (*PutDepotInfoResponse, error) {
	rsp, err := c.PutDepotInfo(ctx, depot, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutDepotInfoResponse(rsp)
}

// GetChannelWithResponse request returning *GetChannelResponse
func (c *ClientWithResponses) GetChannelWithResponse(ctx context.Context, depot DepotName, channel Channel, reqEditors ...RequestEditorFn) (*GetChannelResponse, error) {
	rsp, err := c.GetChannel(ctx, depot, channel, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetChannelResponse(rsp)
}

// PutChannelWithBodyWithResponse request with arbitrary body returning *PutChannelResponse
func (c *ClientWithResponses) PutChannelWithBodyWithResponse(ctx context.Context, depot DepotName, channel Channel, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutChannelResponse, error) {
	rsp, err := c.PutChannelWithBody(ctx, depot, channel, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutChannelResponse(rsp)
}

// ReleaseDepotWithResponse request returning *ReleaseDepotResponse
func (c *ClientWithResponses) ReleaseDepotWithResponse(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*ReleaseDepotResponse, error) {
	rsp, err := c.ReleaseDepot(ctx, depot, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReleaseDepotResponse(rsp)
}

// RollbackDepotWithResponse request returning *RollbackDepotResponse
func (c *ClientWithResponses) RollbackDepotWithResponse(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*RollbackDepotResponse, error) {
	rsp, err := c.RollbackDepot(ctx, depot, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRollbackDepotResponse(rsp)
}

// ParseListDepotsResponse parses an HTTP response from a ListDepotsWithResponse call
func ParseListDepotsResponse(rsp *http.Response) (*ListDepotsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDepotsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DepotList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetDepotResponse parses an HTTP response from a GetDepotWithResponse call
func ParseGetDepotResponse(rsp *http.Response) (*GetDepotResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDepotResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Depot
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePutDepotInfoResponse parses an HTTP response from a PutDepotInfoWithResponse call
func ParsePutDepotInfoResponse(rsp *http.Response) (*PutDepotInfoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutDepotInfoResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Depot
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetChannelResponse parses an HTTP response from a GetChannelWithResponse call
func ParseGetChannelResponse(rsp *http.Response) (*GetChannelResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetChannelResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DepotRelease
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePutChannelResponse parses an HTTP response from a PutChannelWithResponse call
func ParsePutChannelResponse(rsp *http.Response) (*PutChannelResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutChannelResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DepotRelease
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseReleaseDepotResponse parses an HTTP response from a ReleaseDepotWithResponse call
func ParseReleaseDepotResponse(rsp *http.Response) (*ReleaseDepotResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReleaseDepotResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Depot
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseRollbackDepotResponse parses an HTTP response from a RollbackDepotWithResponse call
func ParseRollbackDepotResponse(rsp *http.Response) (*RollbackDepotResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RollbackDepotResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Depot
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all firmware depots
	// (GET /firmwares)
	ListDepots(w http.ResponseWriter, r *http.Request)
	// Get a firmware depot snapshot
	// (GET /firmwares/{depot})
	GetDepot(w http.ResponseWriter, r *http.Request, depot DepotName)
	// Create or update depot info (file manifest)
	// (PUT /firmwares/{depot})
	PutDepotInfo(w http.ResponseWriter, r *http.Request, depot DepotName)
	// Get a specific channel release
	// (GET /firmwares/{depot}/{channel})
	GetChannel(w http.ResponseWriter, r *http.Request, depot DepotName, channel Channel)
	// Upload a firmware release tarball for a channel
	// (PUT /firmwares/{depot}/{channel})
	PutChannel(w http.ResponseWriter, r *http.Request, depot DepotName, channel Channel)
	// Promote testing channel to stable
	// (PUT /firmwares/{depot}:release)
	ReleaseDepot(w http.ResponseWriter, r *http.Request, depot DepotName)
	// Roll back stable channel to the rollback snapshot
	// (PUT /firmwares/{depot}:rollback)
	RollbackDepot(w http.ResponseWriter, r *http.Request, depot DepotName)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all firmware depots
// (GET /firmwares)
func (_ Unimplemented) ListDepots(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a firmware depot snapshot
// (GET /firmwares/{depot})
func (_ Unimplemented) GetDepot(w http.ResponseWriter, r *http.Request, depot DepotName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create or update depot info (file manifest)
// (PUT /firmwares/{depot})
func (_ Unimplemented) PutDepotInfo(w http.ResponseWriter, r *http.Request, depot DepotName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a specific channel release
// (GET /firmwares/{depot}/{channel})
func (_ Unimplemented) GetChannel(w http.ResponseWriter, r *http.Request, depot DepotName, channel Channel) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Upload a firmware release tarball for a channel
// (PUT /firmwares/{depot}/{channel})
func (_ Unimplemented) PutChannel(w http.ResponseWriter, r *http.Request, depot DepotName, channel Channel) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Promote testing channel to stable
// (PUT /firmwares/{depot}:release)
func (_ Unimplemented) ReleaseDepot(w http.ResponseWriter, r *http.Request, depot DepotName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Roll back stable channel to the rollback snapshot
// (PUT /firmwares/{depot}:rollback)
func (_ Unimplemented) RollbackDepot(w http.ResponseWriter, r *http.Request, depot DepotName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListDepots operation middleware
func (siw *ServerInterfaceWrapper) ListDepots(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDepots(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDepot operation middleware
func (siw *ServerInterfaceWrapper) GetDepot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "depot" -------------
	var depot DepotName

	err = runtime.BindStyledParameterWithOptions("simple", "depot", chi.URLParam(r, "depot"), &depot, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "depot", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDepot(w, r, depot)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutDepotInfo operation middleware
func (siw *ServerInterfaceWrapper) PutDepotInfo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "depot" -------------
	var depot DepotName

	err = runtime.BindStyledParameterWithOptions("simple", "depot", chi.URLParam(r, "depot"), &depot, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "depot", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutDepotInfo(w, r, depot)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChannel operation middleware
func (siw *ServerInterfaceWrapper) GetChannel(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "depot" -------------
	var depot DepotName

	err = runtime.BindStyledParameterWithOptions("simple", "depot", chi.URLParam(r, "depot"), &depot, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "depot", Err: err})
		return
	}

	// ------------- Path parameter "channel" -------------
	var channel Channel

	err = runtime.BindStyledParameterWithOptions("simple", "channel", chi.URLParam(r, "channel"), &channel, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channel", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChannel(w, r, depot, channel)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutChannel operation middleware
func (siw *ServerInterfaceWrapper) PutChannel(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "depot" -------------
	var depot DepotName

	err = runtime.BindStyledParameterWithOptions("simple", "depot", chi.URLParam(r, "depot"), &depot, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "depot", Err: err})
		return
	}

	// ------------- Path parameter "channel" -------------
	var channel Channel

	err = runtime.BindStyledParameterWithOptions("simple", "channel", chi.URLParam(r, "channel"), &channel, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channel", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutChannel(w, r, depot, channel)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReleaseDepot operation middleware
func (siw *ServerInterfaceWrapper) ReleaseDepot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "depot" -------------
	var depot DepotName

	err = runtime.BindStyledParameterWithOptions("simple", "depot", chi.URLParam(r, "depot"), &depot, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "depot", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReleaseDepot(w, r, depot)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RollbackDepot operation middleware
func (siw *ServerInterfaceWrapper) RollbackDepot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "depot" -------------
	var depot DepotName

	err = runtime.BindStyledParameterWithOptions("simple", "depot", chi.URLParam(r, "depot"), &depot, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "depot", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RollbackDepot(w, r, depot)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/firmwares", wrapper.ListDepots)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/firmwares/{depot}", wrapper.GetDepot)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/firmwares/{depot}", wrapper.PutDepotInfo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/firmwares/{depot}/{channel}", wrapper.GetChannel)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/firmwares/{depot}/{channel}", wrapper.PutChannel)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/firmwares/{depot}:release", wrapper.ReleaseDepot)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/firmwares/{depot}:rollback", wrapper.RollbackDepot)
	})

	return r
}

type ListDepotsRequestObject struct {
}

type ListDepotsResponseObject interface {
	VisitListDepotsResponse(w http.ResponseWriter) error
}

type ListDepots200JSONResponse DepotList

func (response ListDepots200JSONResponse) VisitListDepotsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListDepots500JSONResponse ErrorResponse

func (response ListDepots500JSONResponse) VisitListDepotsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDepotRequestObject struct {
	Depot DepotName `json:"depot"`
}

type GetDepotResponseObject interface {
	VisitGetDepotResponse(w http.ResponseWriter) error
}

type GetDepot200JSONResponse Depot

func (response GetDepot200JSONResponse) VisitGetDepotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDepot404JSONResponse ErrorResponse

func (response GetDepot404JSONResponse) VisitGetDepotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PutDepotInfoRequestObject struct {
	Depot DepotName `json:"depot"`
	Body  *PutDepotInfoJSONRequestBody
}

type PutDepotInfoResponseObject interface {
	VisitPutDepotInfoResponse(w http.ResponseWriter) error
}

type PutDepotInfo200JSONResponse Depot

func (response PutDepotInfo200JSONResponse) VisitPutDepotInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutDepotInfo400JSONResponse ErrorResponse

func (response PutDepotInfo400JSONResponse) VisitPutDepotInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutDepotInfo409JSONResponse ErrorResponse

func (response PutDepotInfo409JSONResponse) VisitPutDepotInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PutDepotInfo500JSONResponse ErrorResponse

func (response PutDepotInfo500JSONResponse) VisitPutDepotInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetChannelRequestObject struct {
	Depot   DepotName `json:"depot"`
	Channel Channel   `json:"channel"`
}

type GetChannelResponseObject interface {
	VisitGetChannelResponse(w http.ResponseWriter) error
}

type GetChannel200JSONResponse DepotRelease

func (response GetChannel200JSONResponse) VisitGetChannelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetChannel404JSONResponse ErrorResponse

func (response GetChannel404JSONResponse) VisitGetChannelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PutChannelRequestObject struct {
	Depot   DepotName `json:"depot"`
	Channel Channel   `json:"channel"`
	Body    io.Reader
}

type PutChannelResponseObject interface {
	VisitPutChannelResponse(w http.ResponseWriter) error
}

type PutChannel200JSONResponse DepotRelease

func (response PutChannel200JSONResponse) VisitPutChannelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutChannel409JSONResponse ErrorResponse

func (response PutChannel409JSONResponse) VisitPutChannelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ReleaseDepotRequestObject struct {
	Depot DepotName `json:"depot"`
}

type ReleaseDepotResponseObject interface {
	VisitReleaseDepotResponse(w http.ResponseWriter) error
}

type ReleaseDepot200JSONResponse Depot

func (response ReleaseDepot200JSONResponse) VisitReleaseDepotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ReleaseDepot404JSONResponse ErrorResponse

func (response ReleaseDepot404JSONResponse) VisitReleaseDepotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ReleaseDepot409JSONResponse ErrorResponse

func (response ReleaseDepot409JSONResponse) VisitReleaseDepotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ReleaseDepot500JSONResponse ErrorResponse

func (response ReleaseDepot500JSONResponse) VisitReleaseDepotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RollbackDepotRequestObject struct {
	Depot DepotName `json:"depot"`
}

type RollbackDepotResponseObject interface {
	VisitRollbackDepotResponse(w http.ResponseWriter) error
}

type RollbackDepot200JSONResponse Depot

func (response RollbackDepot200JSONResponse) VisitRollbackDepotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RollbackDepot404JSONResponse ErrorResponse

func (response RollbackDepot404JSONResponse) VisitRollbackDepotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RollbackDepot409JSONResponse ErrorResponse

func (response RollbackDepot409JSONResponse) VisitRollbackDepotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type RollbackDepot500JSONResponse ErrorResponse

func (response RollbackDepot500JSONResponse) VisitRollbackDepotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all firmware depots
	// (GET /firmwares)
	ListDepots(ctx context.Context, request ListDepotsRequestObject) (ListDepotsResponseObject, error)
	// Get a firmware depot snapshot
	// (GET /firmwares/{depot})
	GetDepot(ctx context.Context, request GetDepotRequestObject) (GetDepotResponseObject, error)
	// Create or update depot info (file manifest)
	// (PUT /firmwares/{depot})
	PutDepotInfo(ctx context.Context, request PutDepotInfoRequestObject) (PutDepotInfoResponseObject, error)
	// Get a specific channel release
	// (GET /firmwares/{depot}/{channel})
	GetChannel(ctx context.Context, request GetChannelRequestObject) (GetChannelResponseObject, error)
	// Upload a firmware release tarball for a channel
	// (PUT /firmwares/{depot}/{channel})
	PutChannel(ctx context.Context, request PutChannelRequestObject) (PutChannelResponseObject, error)
	// Promote testing channel to stable
	// (PUT /firmwares/{depot}:release)
	ReleaseDepot(ctx context.Context, request ReleaseDepotRequestObject) (ReleaseDepotResponseObject, error)
	// Roll back stable channel to the rollback snapshot
	// (PUT /firmwares/{depot}:rollback)
	RollbackDepot(ctx context.Context, request RollbackDepotRequestObject) (RollbackDepotResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListDepots operation middleware
func (sh *strictHandler) ListDepots(w http.ResponseWriter, r *http.Request) {
	var request ListDepotsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDepots(ctx, request.(ListDepotsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDepots")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDepotsResponseObject); ok {
		if err := validResponse.VisitListDepotsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDepot operation middleware
func (sh *strictHandler) GetDepot(w http.ResponseWriter, r *http.Request, depot DepotName) {
	var request GetDepotRequestObject

	request.Depot = depot

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDepot(ctx, request.(GetDepotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDepot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDepotResponseObject); ok {
		if err := validResponse.VisitGetDepotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutDepotInfo operation middleware
func (sh *strictHandler) PutDepotInfo(w http.ResponseWriter, r *http.Request, depot DepotName) {
	var request PutDepotInfoRequestObject

	request.Depot = depot

	var body PutDepotInfoJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutDepotInfo(ctx, request.(PutDepotInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutDepotInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutDepotInfoResponseObject); ok {
		if err := validResponse.VisitPutDepotInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetChannel operation middleware
func (sh *strictHandler) GetChannel(w http.ResponseWriter, r *http.Request, depot DepotName, channel Channel) {
	var request GetChannelRequestObject

	request.Depot = depot
	request.Channel = channel

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetChannel(ctx, request.(GetChannelRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetChannel")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetChannelResponseObject); ok {
		if err := validResponse.VisitGetChannelResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutChannel operation middleware
func (sh *strictHandler) PutChannel(w http.ResponseWriter, r *http.Request, depot DepotName, channel Channel) {
	var request PutChannelRequestObject

	request.Depot = depot
	request.Channel = channel

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutChannel(ctx, request.(PutChannelRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutChannel")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutChannelResponseObject); ok {
		if err := validResponse.VisitPutChannelResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReleaseDepot operation middleware
func (sh *strictHandler) ReleaseDepot(w http.ResponseWriter, r *http.Request, depot DepotName) {
	var request ReleaseDepotRequestObject

	request.Depot = depot

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReleaseDepot(ctx, request.(ReleaseDepotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReleaseDepot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReleaseDepotResponseObject); ok {
		if err := validResponse.VisitReleaseDepotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RollbackDepot operation middleware
func (sh *strictHandler) RollbackDepot(w http.ResponseWriter, r *http.Request, depot DepotName) {
	var request RollbackDepotRequestObject

	request.Depot = depot

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RollbackDepot(ctx, request.(RollbackDepotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RollbackDepot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RollbackDepotResponseObject); ok {
		if err := validResponse.VisitRollbackDepotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
