// Package admingen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package admingen

// Defines values for Channel.
const (
	Beta     Channel = "beta"
	Rollback Channel = "rollback"
	Stable   Channel = "stable"
	Testing  Channel = "testing"
)

// Valid indicates whether the value is a known member of the Channel enum.
func (e Channel) Valid() bool {
	switch e {
	case Beta:
		return true
	case Rollback:
		return true
	case Stable:
		return true
	case Testing:
		return true
	default:
		return false
	}
}

// Channel defines model for Channel.
type Channel string

// Depot defines model for Depot.
type Depot struct {
	Beta     DepotRelease `json:"beta"`
	Info     DepotInfo    `json:"info"`
	Name     string       `json:"name"`
	Rollback DepotRelease `json:"rollback"`
	Stable   DepotRelease `json:"stable"`
	Testing  DepotRelease `json:"testing"`
}

// DepotFile defines model for DepotFile.
type DepotFile struct {
	Md5    string `json:"md5"`
	Path   string `json:"path"`
	Sha256 string `json:"sha256"`
}

// DepotInfo defines model for DepotInfo.
type DepotInfo struct {
	Files *[]DepotInfoFile `json:"files,omitempty"`
}

// DepotInfoFile defines model for DepotInfoFile.
type DepotInfoFile struct {
	Path string `json:"path"`
}

// DepotList defines model for DepotList.
type DepotList struct {
	Items []Depot `json:"items"`
}

// DepotRelease defines model for DepotRelease.
type DepotRelease struct {
	Channel        *string      `json:"channel,omitempty"`
	Files          *[]DepotFile `json:"files,omitempty"`
	FirmwareSemver string       `json:"firmware_semver"`
}

// ErrorPayload defines model for ErrorPayload.
type ErrorPayload struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorPayload `json:"error"`
}

// DepotName defines model for depotName.
type DepotName = string
