// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Channel = string;

export type Depot = {
    name: string;
    info: DepotInfo;
    rollback: DepotRelease;
    stable: DepotRelease;
    beta: DepotRelease;
    testing: DepotRelease;
};

export type DepotList = {
    items: Array<Depot>;
};

export type DepotInfo = {
    files?: Array<DepotInfoFile>;
};

export type DepotInfoFile = {
    path: string;
};

export type DepotRelease = {
    firmware_semver: string;
    channel?: string;
    files?: Array<DepotFile>;
};

export type DepotFile = {
    path: string;
    sha256: string;
    md5: string;
};

export type GearRole = 'unspecified' | 'admin' | 'peer' | 'device';

export type GearStatus = 'unspecified' | 'active' | 'blocked';

export type GearFirmwareChannel = string;

export type GearCertificationType = 'license' | 'certification';

export type GearCertificationAuthority = 'unknown' | 'ccc' | 'ce' | 'fcc' | 'miit' | 'srrc' | 'rohs' | 'internal';

export type GearImei = {
    name?: string;
    tac: string;
    serial: string;
};

export type GearLabel = {
    key: string;
    value: string;
};

export type GearCertification = {
    type: GearCertificationType;
    authority: GearCertificationAuthority;
    id: string;
    authority_name?: string;
};

export type HardwareInfo = {
    manufacturer?: string;
    model?: string;
    hardware_revision?: string;
    depot?: string;
    firmware_semver?: string;
    imeis?: Array<GearImei>;
    labels?: Array<GearLabel>;
};

export type DeviceInfo = {
    name?: string;
    sn?: string;
    hardware?: HardwareInfo;
};

export type FirmwareConfig = {
    channel?: GearFirmwareChannel;
};

export type Configuration = {
    certifications?: Array<GearCertification>;
    firmware?: FirmwareConfig;
};

export type Registration = {
    public_key: string;
    role: GearRole;
    status: GearStatus;
    auto_registered?: boolean;
    created_at: string;
    updated_at: string;
    approved_at?: string;
};

export type RegistrationList = {
    items: Array<Registration>;
};

export type Runtime = {
    online: boolean;
    last_seen_at: string;
    last_addr?: string;
};

export type RefreshResult = {
    gear: Gear;
    updated_fields?: Array<string>;
    errors?: Array<string>;
};

export type Gear = {
    public_key: string;
    role: GearRole;
    status: GearStatus;
    device: DeviceInfo;
    configuration: Configuration;
    auto_registered?: boolean;
    created_at: string;
    updated_at: string;
    approved_at?: string;
};

export type OtaSummary = {
    depot: string;
    channel: string;
    firmware_semver: string;
    files: Array<DepotFile>;
};

export type PublicKeyResponse = {
    public_key: string;
};

export type ApproveRequest = {
    role: GearRole;
};

export type ErrorResponse = {
    error: ErrorPayload;
};

export type ErrorPayload = {
    code: string;
    message: string;
    details?: {
        [key: string]: unknown;
    };
};

export type RegistrationRequest = {
    public_key: string;
    device: DeviceInfo;
    registration_token?: string;
};

export type RegistrationResult = {
    gear: Gear;
    registration: Registration;
};

export type ServerInfo = {
    public_key: string;
    server_time: number;
    build_commit: string;
};

export type GetServerInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/server-info';
};

export type GetServerInfoErrors = {
    /**
     * Invalid params
     */
    400: ErrorResponse;
};

export type GetServerInfoError = GetServerInfoErrors[keyof GetServerInfoErrors];

export type GetServerInfoResponses = {
    /**
     * Server info
     */
    200: ServerInfo;
};

export type GetServerInfoResponse = GetServerInfoResponses[keyof GetServerInfoResponses];

export type GetInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/info';
};

export type GetInfoErrors = {
    /**
     * Gear not found
     */
    404: ErrorResponse;
};

export type GetInfoError = GetInfoErrors[keyof GetInfoErrors];

export type GetInfoResponses = {
    /**
     * Device info
     */
    200: DeviceInfo;
};

export type GetInfoResponse = GetInfoResponses[keyof GetInfoResponses];

export type PutInfoData = {
    body: DeviceInfo;
    path?: never;
    query?: never;
    url: '/info';
};

export type PutInfoErrors = {
    /**
     * Invalid device info
     */
    400: ErrorResponse;
    /**
     * Gear not found
     */
    404: ErrorResponse;
};

export type PutInfoError = PutInfoErrors[keyof PutInfoErrors];

export type PutInfoResponses = {
    /**
     * Updated device info
     */
    200: DeviceInfo;
};

export type PutInfoResponse = PutInfoResponses[keyof PutInfoResponses];

export type GetRegistrationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/registration';
};

export type GetRegistrationErrors = {
    /**
     * Gear not found
     */
    404: ErrorResponse;
};

export type GetRegistrationError = GetRegistrationErrors[keyof GetRegistrationErrors];

export type GetRegistrationResponses = {
    /**
     * Registration
     */
    200: Registration;
};

export type GetRegistrationResponse = GetRegistrationResponses[keyof GetRegistrationResponses];

export type GetRuntimeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/runtime';
};

export type GetRuntimeErrors = {
    /**
     * Invalid params
     */
    400: ErrorResponse;
};

export type GetRuntimeError = GetRuntimeErrors[keyof GetRuntimeErrors];

export type GetRuntimeResponses = {
    /**
     * Runtime status
     */
    200: Runtime;
};

export type GetRuntimeResponse = GetRuntimeResponses[keyof GetRuntimeResponses];

export type GetConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/config';
};

export type GetConfigErrors = {
    /**
     * Gear not found
     */
    404: ErrorResponse;
};

export type GetConfigError = GetConfigErrors[keyof GetConfigErrors];

export type GetConfigResponses = {
    /**
     * Configuration
     */
    200: Configuration;
};

export type GetConfigResponse = GetConfigResponses[keyof GetConfigResponses];

export type RegisterGearData = {
    body: RegistrationRequest;
    path?: never;
    query?: never;
    url: '/register';
};

export type RegisterGearErrors = {
    /**
     * Invalid params
     */
    400: ErrorResponse;
    /**
     * Gear already exists
     */
    409: ErrorResponse;
};

export type RegisterGearError = RegisterGearErrors[keyof RegisterGearErrors];

export type RegisterGearResponses = {
    /**
     * Registration result
     */
    200: RegistrationResult;
};

export type RegisterGearResponse = RegisterGearResponses[keyof RegisterGearResponses];

export type GetOtaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ota';
};

export type GetOtaErrors = {
    /**
     * OTA not available
     */
    404: ErrorResponse;
};

export type GetOtaError = GetOtaErrors[keyof GetOtaErrors];

export type GetOtaResponses = {
    /**
     * OTA summary
     */
    200: OtaSummary;
};

export type GetOtaResponse = GetOtaResponses[keyof GetOtaResponses];

export type DownloadFirmwareData = {
    body?: never;
    path: {
        /**
         * Percent-encoded firmware file path
         */
        path: string;
    };
    query?: never;
    url: '/download/firmware/{path}';
};

export type DownloadFirmwareErrors = {
    /**
     * Invalid params
     */
    400: ErrorResponse;
    /**
     * Firmware file not found
     */
    404: ErrorResponse;
};

export type DownloadFirmwareError = DownloadFirmwareErrors[keyof DownloadFirmwareErrors];

export type DownloadFirmwareResponses = {
    /**
     * Firmware file
     */
    200: Blob | File;
};

export type DownloadFirmwareResponse = DownloadFirmwareResponses[keyof DownloadFirmwareResponses];
