package: peerpublic
generate:
  fiber-server: true
  strict-server: true
  client: true
  models: true
import-mapping:
  ./types.json: apitypes github.com/GizClaw/gizclaw-go/pkg/gizclaw/api/apitypes
output-options:
  skip-prune: true
