// Package publicgen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package publicgen

import (
	"time"
)

// Defines values for Channel.
const (
	ChannelBeta     Channel = "beta"
	ChannelRollback Channel = "rollback"
	ChannelStable   Channel = "stable"
	ChannelTesting  Channel = "testing"
)

// Valid indicates whether the value is a known member of the Channel enum.
func (e Channel) Valid() bool {
	switch e {
	case ChannelBeta:
		return true
	case ChannelRollback:
		return true
	case ChannelStable:
		return true
	case ChannelTesting:
		return true
	default:
		return false
	}
}

// Defines values for GearCertificationAuthority.
const (
	Ccc      GearCertificationAuthority = "ccc"
	Ce       GearCertificationAuthority = "ce"
	Fcc      GearCertificationAuthority = "fcc"
	Internal GearCertificationAuthority = "internal"
	Miit     GearCertificationAuthority = "miit"
	Rohs     GearCertificationAuthority = "rohs"
	Srrc     GearCertificationAuthority = "srrc"
	Unknown  GearCertificationAuthority = "unknown"
)

// Valid indicates whether the value is a known member of the GearCertificationAuthority enum.
func (e GearCertificationAuthority) Valid() bool {
	switch e {
	case Ccc:
		return true
	case Ce:
		return true
	case Fcc:
		return true
	case Internal:
		return true
	case Miit:
		return true
	case Rohs:
		return true
	case Srrc:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for GearCertificationType.
const (
	Certification GearCertificationType = "certification"
	License       GearCertificationType = "license"
)

// Valid indicates whether the value is a known member of the GearCertificationType enum.
func (e GearCertificationType) Valid() bool {
	switch e {
	case Certification:
		return true
	case License:
		return true
	default:
		return false
	}
}

// Defines values for GearFirmwareChannel.
const (
	GearFirmwareChannelBeta     GearFirmwareChannel = "beta"
	GearFirmwareChannelRollback GearFirmwareChannel = "rollback"
	GearFirmwareChannelStable   GearFirmwareChannel = "stable"
	GearFirmwareChannelTesting  GearFirmwareChannel = "testing"
)

// Valid indicates whether the value is a known member of the GearFirmwareChannel enum.
func (e GearFirmwareChannel) Valid() bool {
	switch e {
	case GearFirmwareChannelBeta:
		return true
	case GearFirmwareChannelRollback:
		return true
	case GearFirmwareChannelStable:
		return true
	case GearFirmwareChannelTesting:
		return true
	default:
		return false
	}
}

// Defines values for GearRole.
const (
	GearRoleAdmin       GearRole = "admin"
	GearRoleDevice      GearRole = "device"
	GearRolePeer        GearRole = "peer"
	GearRoleUnspecified GearRole = "unspecified"
)

// Valid indicates whether the value is a known member of the GearRole enum.
func (e GearRole) Valid() bool {
	switch e {
	case GearRoleAdmin:
		return true
	case GearRoleDevice:
		return true
	case GearRolePeer:
		return true
	case GearRoleUnspecified:
		return true
	default:
		return false
	}
}

// Defines values for GearStatus.
const (
	GearStatusActive      GearStatus = "active"
	GearStatusBlocked     GearStatus = "blocked"
	GearStatusUnspecified GearStatus = "unspecified"
)

// Valid indicates whether the value is a known member of the GearStatus enum.
func (e GearStatus) Valid() bool {
	switch e {
	case GearStatusActive:
		return true
	case GearStatusBlocked:
		return true
	case GearStatusUnspecified:
		return true
	default:
		return false
	}
}

// ApproveRequest defines model for ApproveRequest.
type ApproveRequest struct {
	Role GearRole `json:"role"`
}

// Channel defines model for Channel.
type Channel string

// Configuration defines model for Configuration.
type Configuration struct {
	Certifications *[]GearCertification `json:"certifications,omitempty"`
	Firmware       *FirmwareConfig      `json:"firmware,omitempty"`
}

// Depot defines model for Depot.
type Depot struct {
	Beta     DepotRelease `json:"beta"`
	Info     DepotInfo    `json:"info"`
	Name     string       `json:"name"`
	Rollback DepotRelease `json:"rollback"`
	Stable   DepotRelease `json:"stable"`
	Testing  DepotRelease `json:"testing"`
}

// DepotFile defines model for DepotFile.
type DepotFile struct {
	Md5    string `json:"md5"`
	Path   string `json:"path"`
	Sha256 string `json:"sha256"`
}

// DepotInfo defines model for DepotInfo.
type DepotInfo struct {
	Files *[]DepotInfoFile `json:"files,omitempty"`
}

// DepotInfoFile defines model for DepotInfoFile.
type DepotInfoFile struct {
	Path string `json:"path"`
}

// DepotList defines model for DepotList.
type DepotList struct {
	Items []Depot `json:"items"`
}

// DepotRelease defines model for DepotRelease.
type DepotRelease struct {
	Channel        *string      `json:"channel,omitempty"`
	Files          *[]DepotFile `json:"files,omitempty"`
	FirmwareSemver string       `json:"firmware_semver"`
}

// DeviceInfo defines model for DeviceInfo.
type DeviceInfo struct {
	Hardware *HardwareInfo `json:"hardware,omitempty"`
	Name     *string       `json:"name,omitempty"`
	Sn       *string       `json:"sn,omitempty"`
}

// ErrorPayload defines model for ErrorPayload.
type ErrorPayload struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorPayload `json:"error"`
}

// FirmwareConfig defines model for FirmwareConfig.
type FirmwareConfig struct {
	Channel *GearFirmwareChannel `json:"channel,omitempty"`
}

// Gear defines model for Gear.
type Gear struct {
	ApprovedAt     *time.Time    `json:"approved_at,omitempty"`
	AutoRegistered *bool         `json:"auto_registered,omitempty"`
	Configuration  Configuration `json:"configuration"`
	CreatedAt      time.Time     `json:"created_at"`
	Device         DeviceInfo    `json:"device"`
	PublicKey      string        `json:"public_key"`
	Role           GearRole      `json:"role"`
	Status         GearStatus    `json:"status"`
	UpdatedAt      time.Time     `json:"updated_at"`
}

// GearCertification defines model for GearCertification.
type GearCertification struct {
	Authority     GearCertificationAuthority `json:"authority"`
	AuthorityName *string                    `json:"authority_name,omitempty"`
	Id            string                     `json:"id"`
	Type          GearCertificationType      `json:"type"`
}

// GearCertificationAuthority defines model for GearCertificationAuthority.
type GearCertificationAuthority string

// GearCertificationType defines model for GearCertificationType.
type GearCertificationType string

// GearFirmwareChannel defines model for GearFirmwareChannel.
type GearFirmwareChannel string

// GearIMEI defines model for GearIMEI.
type GearIMEI struct {
	Name   *string `json:"name,omitempty"`
	Serial string  `json:"serial"`
	Tac    string  `json:"tac"`
}

// GearLabel defines model for GearLabel.
type GearLabel struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// GearRole defines model for GearRole.
type GearRole string

// GearStatus defines model for GearStatus.
type GearStatus string

// HardwareInfo defines model for HardwareInfo.
type HardwareInfo struct {
	Depot            *string      `json:"depot,omitempty"`
	FirmwareSemver   *string      `json:"firmware_semver,omitempty"`
	HardwareRevision *string      `json:"hardware_revision,omitempty"`
	Imeis            *[]GearIMEI  `json:"imeis,omitempty"`
	Labels           *[]GearLabel `json:"labels,omitempty"`
	Manufacturer     *string      `json:"manufacturer,omitempty"`
	Model            *string      `json:"model,omitempty"`
}

// OTASummary defines model for OTASummary.
type OTASummary struct {
	Channel        string      `json:"channel"`
	Depot          string      `json:"depot"`
	Files          []DepotFile `json:"files"`
	FirmwareSemver string      `json:"firmware_semver"`
}

// PublicKeyResponse defines model for PublicKeyResponse.
type PublicKeyResponse struct {
	PublicKey string `json:"public_key"`
}

// RefreshResult defines model for RefreshResult.
type RefreshResult struct {
	Errors        *[]string `json:"errors,omitempty"`
	Gear          Gear      `json:"gear"`
	UpdatedFields *[]string `json:"updated_fields,omitempty"`
}

// Registration defines model for Registration.
type Registration struct {
	ApprovedAt     *time.Time `json:"approved_at,omitempty"`
	AutoRegistered *bool      `json:"auto_registered,omitempty"`
	CreatedAt      time.Time  `json:"created_at"`
	PublicKey      string     `json:"public_key"`
	Role           GearRole   `json:"role"`
	Status         GearStatus `json:"status"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

// RegistrationList defines model for RegistrationList.
type RegistrationList struct {
	Items []Registration `json:"items"`
}

// RegistrationRequest defines model for RegistrationRequest.
type RegistrationRequest struct {
	Device            DeviceInfo `json:"device"`
	PublicKey         string     `json:"public_key"`
	RegistrationToken *string    `json:"registration_token,omitempty"`
}

// RegistrationResult defines model for RegistrationResult.
type RegistrationResult struct {
	Gear         Gear         `json:"gear"`
	Registration Registration `json:"registration"`
}

// Runtime defines model for Runtime.
type Runtime struct {
	LastAddr   *string   `json:"last_addr,omitempty"`
	LastSeenAt time.Time `json:"last_seen_at"`
	Online     bool      `json:"online"`
}

// ServerInfo defines model for ServerInfo.
type ServerInfo struct {
	BuildCommit string `json:"build_commit"`
	PublicKey   string `json:"public_key"`
	ServerTime  int64  `json:"server_time"`
}
