// This file is auto-generated by @hey-api/openapi-ts

export { getIdentifiers, getInfo, getVersion, type Options } from './sdk.gen';
export type { ClientOptions, GearImei, GearLabel, GetIdentifiersData, GetIdentifiersErrors, GetIdentifiersResponse, GetIdentifiersResponses, GetInfoData, GetInfoErrors, GetInfoResponse, GetInfoResponses, GetVersionData, GetVersionErrors, GetVersionResponse, GetVersionResponses, RefreshIdentifiers, RefreshInfo, RefreshVersion } from './types.gen';
