// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetIdentifiersData, GetIdentifiersErrors, GetIdentifiersResponses, GetInfoData, GetInfoErrors, GetInfoResponses, GetVersionData, GetVersionErrors, GetVersionResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get basic device information
 */
export const getInfo = <ThrowOnError extends boolean = false>(options?: Options<GetInfoData, ThrowOnError>) => (options?.client ?? client).get<GetInfoResponses, GetInfoErrors, ThrowOnError>({ url: '/info', ...options });

/**
 * Get device identifiers
 */
export const getIdentifiers = <ThrowOnError extends boolean = false>(options?: Options<GetIdentifiersData, ThrowOnError>) => (options?.client ?? client).get<GetIdentifiersResponses, GetIdentifiersErrors, ThrowOnError>({ url: '/identifiers', ...options });

/**
 * Get current firmware version metadata
 */
export const getVersion = <ThrowOnError extends boolean = false>(options?: Options<GetVersionData, ThrowOnError>) => (options?.client ?? client).get<GetVersionResponses, GetVersionErrors, ThrowOnError>({ url: '/version', ...options });
