// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type RefreshInfo = {
    name?: string;
    manufacturer?: string;
    model?: string;
    hardware_revision?: string;
};

export type RefreshIdentifiers = {
    sn?: string;
    imeis?: Array<GearImei>;
    labels?: Array<GearLabel>;
};

export type RefreshVersion = {
    depot?: string;
    firmware_semver?: string;
};

export type GearImei = {
    name?: string;
    tac: string;
    serial: string;
};

export type GearLabel = {
    key: string;
    value: string;
};

export type GetInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/info';
};

export type GetInfoErrors = {
    /**
     * Unexpected error
     */
    default: unknown;
};

export type GetInfoResponses = {
    /**
     * Basic device information
     */
    200: RefreshInfo;
};

export type GetInfoResponse = GetInfoResponses[keyof GetInfoResponses];

export type GetIdentifiersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identifiers';
};

export type GetIdentifiersErrors = {
    /**
     * Unexpected error
     */
    default: unknown;
};

export type GetIdentifiersResponses = {
    /**
     * Device identifiers
     */
    200: RefreshIdentifiers;
};

export type GetIdentifiersResponse = GetIdentifiersResponses[keyof GetIdentifiersResponses];

export type GetVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/version';
};

export type GetVersionErrors = {
    /**
     * Unexpected error
     */
    default: unknown;
};

export type GetVersionResponses = {
    /**
     * Firmware version metadata
     */
    200: RefreshVersion;
};

export type GetVersionResponse = GetVersionResponses[keyof GetVersionResponses];
