// Package adminservice provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package adminservice

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

// Defines values for Channel.
const (
	Beta     Channel = "beta"
	Rollback Channel = "rollback"
	Stable   Channel = "stable"
	Testing  Channel = "testing"
)

// Valid indicates whether the value is a known member of the Channel enum.
func (e Channel) Valid() bool {
	switch e {
	case Beta:
		return true
	case Rollback:
		return true
	case Stable:
		return true
	case Testing:
		return true
	default:
		return false
	}
}

// Channel defines model for Channel.
type Channel string

// Depot defines model for Depot.
type Depot struct {
	Beta     DepotRelease `json:"beta"`
	Info     DepotInfo    `json:"info"`
	Name     string       `json:"name"`
	Rollback DepotRelease `json:"rollback"`
	Stable   DepotRelease `json:"stable"`
	Testing  DepotRelease `json:"testing"`
}

// DepotFile defines model for DepotFile.
type DepotFile struct {
	Md5    string `json:"md5"`
	Path   string `json:"path"`
	Sha256 string `json:"sha256"`
}

// DepotInfo defines model for DepotInfo.
type DepotInfo struct {
	Files *[]DepotInfoFile `json:"files,omitempty"`
}

// DepotInfoFile defines model for DepotInfoFile.
type DepotInfoFile struct {
	Path string `json:"path"`
}

// DepotList defines model for DepotList.
type DepotList struct {
	Items []Depot `json:"items"`
}

// DepotRelease defines model for DepotRelease.
type DepotRelease struct {
	Channel        *string      `json:"channel,omitempty"`
	Files          *[]DepotFile `json:"files,omitempty"`
	FirmwareSemver string       `json:"firmware_semver"`
}

// ErrorPayload defines model for ErrorPayload.
type ErrorPayload struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorPayload `json:"error"`
}

// DepotName defines model for depotName.
type DepotName = string

// PutDepotInfoJSONRequestBody defines body for PutDepotInfo for application/json ContentType.
type PutDepotInfoJSONRequestBody = DepotInfo

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// GeneratedClient conforms to the OpenAPI3 specification for this service.
type GeneratedClient struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*GeneratedClient) error

// NewGeneratedClient creates a new generated client with reasonable defaults.
func NewGeneratedClient(server string, opts ...ClientOption) (*GeneratedClient, error) {
	// create a client with sane default values
	client := GeneratedClient{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *GeneratedClient) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *GeneratedClient) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListDepots request
	ListDepots(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDepot request
	GetDepot(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutDepotInfoWithBody request with any body
	PutDepotInfoWithBody(ctx context.Context, depot DepotName, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutDepotInfo(ctx context.Context, depot DepotName, body PutDepotInfoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetChannel request
	GetChannel(ctx context.Context, depot DepotName, channel Channel, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutChannelWithBody request with any body
	PutChannelWithBody(ctx context.Context, depot DepotName, channel Channel, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReleaseDepot request
	ReleaseDepot(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RollbackDepot request
	RollbackDepot(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *GeneratedClient) ListDepots(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDepotsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *GeneratedClient) GetDepot(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDepotRequest(c.Server, depot)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *GeneratedClient) PutDepotInfoWithBody(ctx context.Context, depot DepotName, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutDepotInfoRequestWithBody(c.Server, depot, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *GeneratedClient) PutDepotInfo(ctx context.Context, depot DepotName, body PutDepotInfoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutDepotInfoRequest(c.Server, depot, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *GeneratedClient) GetChannel(ctx context.Context, depot DepotName, channel Channel, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetChannelRequest(c.Server, depot, channel)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *GeneratedClient) PutChannelWithBody(ctx context.Context, depot DepotName, channel Channel, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutChannelRequestWithBody(c.Server, depot, channel, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *GeneratedClient) ReleaseDepot(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReleaseDepotRequest(c.Server, depot)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *GeneratedClient) RollbackDepot(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRollbackDepotRequest(c.Server, depot)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListDepotsRequest generates requests for ListDepots
func NewListDepotsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/firmwares")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDepotRequest generates requests for GetDepot
func NewGetDepotRequest(server string, depot DepotName) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "depot", depot, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/firmwares/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutDepotInfoRequest calls the generic PutDepotInfo builder with application/json body
func NewPutDepotInfoRequest(server string, depot DepotName, body PutDepotInfoJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutDepotInfoRequestWithBody(server, depot, "application/json", bodyReader)
}

// NewPutDepotInfoRequestWithBody generates requests for PutDepotInfo with any type of body
func NewPutDepotInfoRequestWithBody(server string, depot DepotName, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "depot", depot, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/firmwares/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetChannelRequest generates requests for GetChannel
func NewGetChannelRequest(server string, depot DepotName, channel Channel) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "depot", depot, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "channel", channel, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/firmwares/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutChannelRequestWithBody generates requests for PutChannel with any type of body
func NewPutChannelRequestWithBody(server string, depot DepotName, channel Channel, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "depot", depot, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "channel", channel, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/firmwares/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewReleaseDepotRequest generates requests for ReleaseDepot
func NewReleaseDepotRequest(server string, depot DepotName) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "depot", depot, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/firmwares/%s:release", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRollbackDepotRequest generates requests for RollbackDepot
func NewRollbackDepotRequest(server string, depot DepotName) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "depot", depot, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/firmwares/%s:rollback", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *GeneratedClient) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewGeneratedClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *GeneratedClient) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListDepotsWithResponse request
	ListDepotsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDepotsResponse, error)

	// GetDepotWithResponse request
	GetDepotWithResponse(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*GetDepotResponse, error)

	// PutDepotInfoWithBodyWithResponse request with any body
	PutDepotInfoWithBodyWithResponse(ctx context.Context, depot DepotName, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutDepotInfoResponse, error)

	PutDepotInfoWithResponse(ctx context.Context, depot DepotName, body PutDepotInfoJSONRequestBody, reqEditors ...RequestEditorFn) (*PutDepotInfoResponse, error)

	// GetChannelWithResponse request
	GetChannelWithResponse(ctx context.Context, depot DepotName, channel Channel, reqEditors ...RequestEditorFn) (*GetChannelResponse, error)

	// PutChannelWithBodyWithResponse request with any body
	PutChannelWithBodyWithResponse(ctx context.Context, depot DepotName, channel Channel, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutChannelResponse, error)

	// ReleaseDepotWithResponse request
	ReleaseDepotWithResponse(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*ReleaseDepotResponse, error)

	// RollbackDepotWithResponse request
	RollbackDepotWithResponse(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*RollbackDepotResponse, error)
}

type ListDepotsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DepotList
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListDepotsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDepotsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDepotResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Depot
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetDepotResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDepotResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutDepotInfoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Depot
	JSON400      *ErrorResponse
	JSON409      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PutDepotInfoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutDepotInfoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetChannelResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DepotRelease
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetChannelResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetChannelResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutChannelResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DepotRelease
	JSON409      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PutChannelResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutChannelResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ReleaseDepotResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Depot
	JSON404      *ErrorResponse
	JSON409      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ReleaseDepotResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReleaseDepotResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RollbackDepotResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Depot
	JSON404      *ErrorResponse
	JSON409      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r RollbackDepotResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RollbackDepotResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListDepotsWithResponse request returning *ListDepotsResponse
func (c *ClientWithResponses) ListDepotsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDepotsResponse, error) {
	rsp, err := c.ListDepots(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDepotsResponse(rsp)
}

// GetDepotWithResponse request returning *GetDepotResponse
func (c *ClientWithResponses) GetDepotWithResponse(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*GetDepotResponse, error) {
	rsp, err := c.GetDepot(ctx, depot, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDepotResponse(rsp)
}

// PutDepotInfoWithBodyWithResponse request with arbitrary body returning *PutDepotInfoResponse
func (c *ClientWithResponses) PutDepotInfoWithBodyWithResponse(ctx context.Context, depot DepotName, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutDepotInfoResponse, error) {
	rsp, err := c.PutDepotInfoWithBody(ctx, depot, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutDepotInfoResponse(rsp)
}

func (c *ClientWithResponses) PutDepotInfoWithResponse(ctx context.Context, depot DepotName, body PutDepotInfoJSONRequestBody, reqEditors ...RequestEditorFn) (*PutDepotInfoResponse, error) {
	rsp, err := c.PutDepotInfo(ctx, depot, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutDepotInfoResponse(rsp)
}

// GetChannelWithResponse request returning *GetChannelResponse
func (c *ClientWithResponses) GetChannelWithResponse(ctx context.Context, depot DepotName, channel Channel, reqEditors ...RequestEditorFn) (*GetChannelResponse, error) {
	rsp, err := c.GetChannel(ctx, depot, channel, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetChannelResponse(rsp)
}

// PutChannelWithBodyWithResponse request with arbitrary body returning *PutChannelResponse
func (c *ClientWithResponses) PutChannelWithBodyWithResponse(ctx context.Context, depot DepotName, channel Channel, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutChannelResponse, error) {
	rsp, err := c.PutChannelWithBody(ctx, depot, channel, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutChannelResponse(rsp)
}

// ReleaseDepotWithResponse request returning *ReleaseDepotResponse
func (c *ClientWithResponses) ReleaseDepotWithResponse(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*ReleaseDepotResponse, error) {
	rsp, err := c.ReleaseDepot(ctx, depot, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReleaseDepotResponse(rsp)
}

// RollbackDepotWithResponse request returning *RollbackDepotResponse
func (c *ClientWithResponses) RollbackDepotWithResponse(ctx context.Context, depot DepotName, reqEditors ...RequestEditorFn) (*RollbackDepotResponse, error) {
	rsp, err := c.RollbackDepot(ctx, depot, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRollbackDepotResponse(rsp)
}

// ParseListDepotsResponse parses an HTTP response from a ListDepotsWithResponse call
func ParseListDepotsResponse(rsp *http.Response) (*ListDepotsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDepotsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DepotList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetDepotResponse parses an HTTP response from a GetDepotWithResponse call
func ParseGetDepotResponse(rsp *http.Response) (*GetDepotResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDepotResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Depot
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePutDepotInfoResponse parses an HTTP response from a PutDepotInfoWithResponse call
func ParsePutDepotInfoResponse(rsp *http.Response) (*PutDepotInfoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutDepotInfoResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Depot
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetChannelResponse parses an HTTP response from a GetChannelWithResponse call
func ParseGetChannelResponse(rsp *http.Response) (*GetChannelResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetChannelResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DepotRelease
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePutChannelResponse parses an HTTP response from a PutChannelWithResponse call
func ParsePutChannelResponse(rsp *http.Response) (*PutChannelResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutChannelResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DepotRelease
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseReleaseDepotResponse parses an HTTP response from a ReleaseDepotWithResponse call
func ParseReleaseDepotResponse(rsp *http.Response) (*ReleaseDepotResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReleaseDepotResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Depot
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseRollbackDepotResponse parses an HTTP response from a RollbackDepotWithResponse call
func ParseRollbackDepotResponse(rsp *http.Response) (*RollbackDepotResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RollbackDepotResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Depot
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all firmware depots
	// (GET /firmwares)
	ListDepots(c *fiber.Ctx) error
	// Get a firmware depot snapshot
	// (GET /firmwares/{depot})
	GetDepot(c *fiber.Ctx, depot DepotName) error
	// Create or update depot info (file manifest)
	// (PUT /firmwares/{depot})
	PutDepotInfo(c *fiber.Ctx, depot DepotName) error
	// Get a specific channel release
	// (GET /firmwares/{depot}/{channel})
	GetChannel(c *fiber.Ctx, depot DepotName, channel Channel) error
	// Upload a firmware release tarball for a channel
	// (PUT /firmwares/{depot}/{channel})
	PutChannel(c *fiber.Ctx, depot DepotName, channel Channel) error
	// Promote testing channel to stable
	// (PUT /firmwares/{depot}:release)
	ReleaseDepot(c *fiber.Ctx, depot DepotName) error
	// Roll back stable channel to the rollback snapshot
	// (PUT /firmwares/{depot}:rollback)
	RollbackDepot(c *fiber.Ctx, depot DepotName) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// ListDepots operation middleware
func (siw *ServerInterfaceWrapper) ListDepots(c *fiber.Ctx) error {

	return siw.Handler.ListDepots(c)
}

// GetDepot operation middleware
func (siw *ServerInterfaceWrapper) GetDepot(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "depot" -------------
	var depot DepotName

	err = runtime.BindStyledParameterWithOptions("simple", "depot", c.Params("depot"), &depot, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter depot: %w", err).Error())
	}

	return siw.Handler.GetDepot(c, depot)
}

// PutDepotInfo operation middleware
func (siw *ServerInterfaceWrapper) PutDepotInfo(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "depot" -------------
	var depot DepotName

	err = runtime.BindStyledParameterWithOptions("simple", "depot", c.Params("depot"), &depot, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter depot: %w", err).Error())
	}

	return siw.Handler.PutDepotInfo(c, depot)
}

// GetChannel operation middleware
func (siw *ServerInterfaceWrapper) GetChannel(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "depot" -------------
	var depot DepotName

	err = runtime.BindStyledParameterWithOptions("simple", "depot", c.Params("depot"), &depot, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter depot: %w", err).Error())
	}

	// ------------- Path parameter "channel" -------------
	var channel Channel

	err = runtime.BindStyledParameterWithOptions("simple", "channel", c.Params("channel"), &channel, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter channel: %w", err).Error())
	}

	return siw.Handler.GetChannel(c, depot, channel)
}

// PutChannel operation middleware
func (siw *ServerInterfaceWrapper) PutChannel(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "depot" -------------
	var depot DepotName

	err = runtime.BindStyledParameterWithOptions("simple", "depot", c.Params("depot"), &depot, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter depot: %w", err).Error())
	}

	// ------------- Path parameter "channel" -------------
	var channel Channel

	err = runtime.BindStyledParameterWithOptions("simple", "channel", c.Params("channel"), &channel, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter channel: %w", err).Error())
	}

	return siw.Handler.PutChannel(c, depot, channel)
}

// ReleaseDepot operation middleware
func (siw *ServerInterfaceWrapper) ReleaseDepot(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "depot" -------------
	var depot DepotName

	err = runtime.BindStyledParameterWithOptions("simple", "depot", c.Params("depot"), &depot, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter depot: %w", err).Error())
	}

	return siw.Handler.ReleaseDepot(c, depot)
}

// RollbackDepot operation middleware
func (siw *ServerInterfaceWrapper) RollbackDepot(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "depot" -------------
	var depot DepotName

	err = runtime.BindStyledParameterWithOptions("simple", "depot", c.Params("depot"), &depot, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter depot: %w", err).Error())
	}

	return siw.Handler.RollbackDepot(c, depot)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/firmwares", wrapper.ListDepots)

	router.Get(options.BaseURL+"/firmwares/:depot", wrapper.GetDepot)

	router.Put(options.BaseURL+"/firmwares/:depot", wrapper.PutDepotInfo)

	router.Get(options.BaseURL+"/firmwares/:depot/:channel", wrapper.GetChannel)

	router.Put(options.BaseURL+"/firmwares/:depot/:channel", wrapper.PutChannel)

	router.Put(options.BaseURL+"/firmwares/:depot:release", wrapper.ReleaseDepot)

	router.Put(options.BaseURL+"/firmwares/:depot:rollback", wrapper.RollbackDepot)

}

type ListDepotsRequestObject struct {
}

type ListDepotsResponseObject interface {
	VisitListDepotsResponse(ctx *fiber.Ctx) error
}

type ListDepots200JSONResponse DepotList

func (response ListDepots200JSONResponse) VisitListDepotsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type ListDepots500JSONResponse ErrorResponse

func (response ListDepots500JSONResponse) VisitListDepotsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetDepotRequestObject struct {
	Depot DepotName `json:"depot"`
}

type GetDepotResponseObject interface {
	VisitGetDepotResponse(ctx *fiber.Ctx) error
}

type GetDepot200JSONResponse Depot

func (response GetDepot200JSONResponse) VisitGetDepotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetDepot404JSONResponse ErrorResponse

func (response GetDepot404JSONResponse) VisitGetDepotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type PutDepotInfoRequestObject struct {
	Depot DepotName `json:"depot"`
	Body  *PutDepotInfoJSONRequestBody
}

type PutDepotInfoResponseObject interface {
	VisitPutDepotInfoResponse(ctx *fiber.Ctx) error
}

type PutDepotInfo200JSONResponse Depot

func (response PutDepotInfo200JSONResponse) VisitPutDepotInfoResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type PutDepotInfo400JSONResponse ErrorResponse

func (response PutDepotInfo400JSONResponse) VisitPutDepotInfoResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type PutDepotInfo409JSONResponse ErrorResponse

func (response PutDepotInfo409JSONResponse) VisitPutDepotInfoResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type PutDepotInfo500JSONResponse ErrorResponse

func (response PutDepotInfo500JSONResponse) VisitPutDepotInfoResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetChannelRequestObject struct {
	Depot   DepotName `json:"depot"`
	Channel Channel   `json:"channel"`
}

type GetChannelResponseObject interface {
	VisitGetChannelResponse(ctx *fiber.Ctx) error
}

type GetChannel200JSONResponse DepotRelease

func (response GetChannel200JSONResponse) VisitGetChannelResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetChannel404JSONResponse ErrorResponse

func (response GetChannel404JSONResponse) VisitGetChannelResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type PutChannelRequestObject struct {
	Depot   DepotName `json:"depot"`
	Channel Channel   `json:"channel"`
	Body    io.Reader
}

type PutChannelResponseObject interface {
	VisitPutChannelResponse(ctx *fiber.Ctx) error
}

type PutChannel200JSONResponse DepotRelease

func (response PutChannel200JSONResponse) VisitPutChannelResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type PutChannel409JSONResponse ErrorResponse

func (response PutChannel409JSONResponse) VisitPutChannelResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type ReleaseDepotRequestObject struct {
	Depot DepotName `json:"depot"`
}

type ReleaseDepotResponseObject interface {
	VisitReleaseDepotResponse(ctx *fiber.Ctx) error
}

type ReleaseDepot200JSONResponse Depot

func (response ReleaseDepot200JSONResponse) VisitReleaseDepotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type ReleaseDepot404JSONResponse ErrorResponse

func (response ReleaseDepot404JSONResponse) VisitReleaseDepotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type ReleaseDepot409JSONResponse ErrorResponse

func (response ReleaseDepot409JSONResponse) VisitReleaseDepotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type ReleaseDepot500JSONResponse ErrorResponse

func (response ReleaseDepot500JSONResponse) VisitReleaseDepotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type RollbackDepotRequestObject struct {
	Depot DepotName `json:"depot"`
}

type RollbackDepotResponseObject interface {
	VisitRollbackDepotResponse(ctx *fiber.Ctx) error
}

type RollbackDepot200JSONResponse Depot

func (response RollbackDepot200JSONResponse) VisitRollbackDepotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type RollbackDepot404JSONResponse ErrorResponse

func (response RollbackDepot404JSONResponse) VisitRollbackDepotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type RollbackDepot409JSONResponse ErrorResponse

func (response RollbackDepot409JSONResponse) VisitRollbackDepotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type RollbackDepot500JSONResponse ErrorResponse

func (response RollbackDepot500JSONResponse) VisitRollbackDepotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all firmware depots
	// (GET /firmwares)
	ListDepots(ctx context.Context, request ListDepotsRequestObject) (ListDepotsResponseObject, error)
	// Get a firmware depot snapshot
	// (GET /firmwares/{depot})
	GetDepot(ctx context.Context, request GetDepotRequestObject) (GetDepotResponseObject, error)
	// Create or update depot info (file manifest)
	// (PUT /firmwares/{depot})
	PutDepotInfo(ctx context.Context, request PutDepotInfoRequestObject) (PutDepotInfoResponseObject, error)
	// Get a specific channel release
	// (GET /firmwares/{depot}/{channel})
	GetChannel(ctx context.Context, request GetChannelRequestObject) (GetChannelResponseObject, error)
	// Upload a firmware release tarball for a channel
	// (PUT /firmwares/{depot}/{channel})
	PutChannel(ctx context.Context, request PutChannelRequestObject) (PutChannelResponseObject, error)
	// Promote testing channel to stable
	// (PUT /firmwares/{depot}:release)
	ReleaseDepot(ctx context.Context, request ReleaseDepotRequestObject) (ReleaseDepotResponseObject, error)
	// Roll back stable channel to the rollback snapshot
	// (PUT /firmwares/{depot}:rollback)
	RollbackDepot(ctx context.Context, request RollbackDepotRequestObject) (RollbackDepotResponseObject, error)
}

type StrictHandlerFunc func(ctx *fiber.Ctx, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListDepots operation middleware
func (sh *strictHandler) ListDepots(ctx *fiber.Ctx) error {
	var request ListDepotsRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.ListDepots(ctx.UserContext(), request.(ListDepotsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDepots")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(ListDepotsResponseObject); ok {
		if err := validResponse.VisitListDepotsResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetDepot operation middleware
func (sh *strictHandler) GetDepot(ctx *fiber.Ctx, depot DepotName) error {
	var request GetDepotRequestObject

	request.Depot = depot

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetDepot(ctx.UserContext(), request.(GetDepotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDepot")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetDepotResponseObject); ok {
		if err := validResponse.VisitGetDepotResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PutDepotInfo operation middleware
func (sh *strictHandler) PutDepotInfo(ctx *fiber.Ctx, depot DepotName) error {
	var request PutDepotInfoRequestObject

	request.Depot = depot

	var body PutDepotInfoJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.PutDepotInfo(ctx.UserContext(), request.(PutDepotInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutDepotInfo")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(PutDepotInfoResponseObject); ok {
		if err := validResponse.VisitPutDepotInfoResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetChannel operation middleware
func (sh *strictHandler) GetChannel(ctx *fiber.Ctx, depot DepotName, channel Channel) error {
	var request GetChannelRequestObject

	request.Depot = depot
	request.Channel = channel

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetChannel(ctx.UserContext(), request.(GetChannelRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetChannel")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetChannelResponseObject); ok {
		if err := validResponse.VisitGetChannelResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PutChannel operation middleware
func (sh *strictHandler) PutChannel(ctx *fiber.Ctx, depot DepotName, channel Channel) error {
	var request PutChannelRequestObject

	request.Depot = depot
	request.Channel = channel

	request.Body = bytes.NewReader(ctx.Request().Body())

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.PutChannel(ctx.UserContext(), request.(PutChannelRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutChannel")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(PutChannelResponseObject); ok {
		if err := validResponse.VisitPutChannelResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ReleaseDepot operation middleware
func (sh *strictHandler) ReleaseDepot(ctx *fiber.Ctx, depot DepotName) error {
	var request ReleaseDepotRequestObject

	request.Depot = depot

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.ReleaseDepot(ctx.UserContext(), request.(ReleaseDepotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReleaseDepot")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(ReleaseDepotResponseObject); ok {
		if err := validResponse.VisitReleaseDepotResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RollbackDepot operation middleware
func (sh *strictHandler) RollbackDepot(ctx *fiber.Ctx, depot DepotName) error {
	var request RollbackDepotRequestObject

	request.Depot = depot

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.RollbackDepot(ctx.UserContext(), request.(RollbackDepotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RollbackDepot")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(RollbackDepotResponseObject); ok {
		if err := validResponse.VisitRollbackDepotResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
